### ISSUE TITLE
CSS: @import url is on top of css.php and gets ignored/replaced

### ISSUE THREAD

**Issue by mbudget** [splitbrain/dokuwiki#1016]
Hello

I made a userall.css in the folder animal/conf. In that CSS file I import via @import url ("") an external CSS file, which schould be used for the animal wiki.

Dokuwiki imports the CSS file and places to the top of css.php. Because of that the imported CSS file gets overwritten by the main style sheet of dokuwiki and doesn't apply. So the correct way would be that the imported style sheet is on the bottom of css.php. 

It would be nice if this could be fixed, so I don't have to write directly in to the userall.css.

**Comment by splitbrain** [comment]
See http://www.w3.org/TR/CSS21/cascade.html#at-import

> ```any @import rules must precede all other rules (except the @charset rule, if present).```

imports *have* to be at the top or will be ignored by the browser.

**Comment by eins78** [comment]
Handling the `userall.css` this way kind of defeats the purpose of it, since the default dokuwiki styles are placed after the user styles (thus mostly overidding them).

@splitbrain is correct that `@import` directives have to be at the top of the file.
But: The use case here is to have a `userall.css` which only has a single `@import` statement referencing an external stylesheet but still overrides the dokuwiki styles. This is not currently possible with dokuwiki because it always creates 1 CSS file.

I can see only one way to achieve this result: Instead of passing `userall.css` through `css.php` and doing all the processing, a second `<link>` element should be added to the `<head>`, after the one referencing `css.php`.

Since that seem like a rather large change, we would also be happy with *a new kind of* userstyle which behaves in the way described above (for example `userall_after.css` or something like it).

**Comment by Klap-in** [comment]
When a less-file is imported (like `@import yourfile.less`), then css.php will replace the syntax by the content of the yourfile.less.

When not a .less file is imported, then it is handle as normal css.

**Comment by eins78** [comment]
> If a less-file is imported (like @import yourfile.less), then css.php will replace the syntax by the content of the yourfile.less.
@Klap-in the documentation says that this feature is 'develonly', so I assumed that it is not a viable option for using it in production in a farm setup. Did I misunderstand the term?

**Comment by Klap-in** [comment]
Less support is available since 2013-12-08 “Binky” see also https://www.dokuwiki.org/devel:less

The develonly note at https://www.dokuwiki.org/devel:css#user_styles is only about the inclusion of 'user styles'. If you have the development version, you can put .less version of the user styles in the conf/ folder as well.
