### ISSUE TITLE
ACLs when using authad shoudl be case sensitive

### ISSUE THREAD

**Issue by aseques** [splitbrain/dokuwiki#1060]
I discovered after several attempts that the ACLs are being saved as lowercase in the acl.auth.php file, that makes the matching to the real groupnames fail every time.
I replaced the group name in acl.auth.php and it's working as expected now.
Once found the issue I've looked for previously error reports and couldn't find anything (strange because I guess it's quite common)
Another user with the same issue [here](http://nosq.com/2005/08/ldap-activedirectory-and-dokuwiki/comment-page-1/#comment-743)
Is this really a bug or I just did something terribly wrong?

**Comment by splitbrain** [comment]
How did you create the ACLs? The AD backend will automatically lowercase user and group names coming from the backend. As long as you use the ACL manager to create ACLs they should always match what your backend delivers.

**Comment by aseques** [comment]
I created the ACL from the frontend initially, and I found out that the letters were lowercased, unless they where properly cased (as in the AD group name) it would't set the users in the proper ACL rules (they all fell into @user)
The only think I manually  edited was the superuser group (that matches the group I am using for users)

**Comment by igittigitt** [comment]
I make heavy use of AD-Groups/Users using the latest Dokuwiki and authad-plugin but did not had such problems yet. As splitbrain said, both names are mangeled inside DW, the one in ACLs and the one fetched by adLDAP lib inside authad. No only case, but also some special chars. So they should match. Besides this, Windows itself is not case sensitive at all (except the password).
So, changeing case in ACL should'nt have any effect. The underlying adLDAP-Lib has'nt case settings either. Are you shure that you only changed case and nothing else? Could you supply an real example? Does your Dokuwiki runs on Linux or Windows?
The issue you linked as about 9 years old(!) Things have changed heavily under the hoode since then...

**Comment by aseques** [comment]
Hi @igittigitt I really don't know what caused it, but it got fixed by changing the group names to the same capitalization everywhere (it was G_Systems for the group "G Systems"). Now I changed the group names to non-capitals and it is still working too.
My guess is that the differing capitals in group names made that the the newer users weren't given a groupname accepted by the acl
About the old time of the issue linked I was pretty skeptic too (see last line on my post) but It was quite close to my issue.
Anyway, now it works without having done any changes, so it was probably my fault somehow.

**Comment by axel1973** [comment]
it seems i have the same problem, that authad does not show/get any ad Groupmembership. So i tried this solution/suggestion to make the ACL entries for the AD Groups uppercase as it is in our AD Domain. But it did not worked or changed anything. i tried it on  2015-08-10a "Detritus" where i still have the problems that i can authenticate, but since there are no group information pulled from the AD (without any error messages within DW :( ) i cannot work with ACLs or anything on our "closed usergroup wiki".
