### ISSUE TITLE
"Code Text" breaks code logic

### ISSUE THREAD

**Issue by The-Judge** [splitbrain/dokuwiki#1063]
Dokuwiki's "Code Text" option (which is generated when text is put between two `''` occourances) is intended for highlighting (rather) short lines of code, such as shell commands or such. Also, this should be formated in easy to read and copy & pasteable output.

Many programs use double-"-" notation for their commandline (as in `ls --all` for example).

As you can see in this GitHub-Bugtracker, which uses Markdown formating for rendering text, these double-dashes are preserved, since they're essential for this code to be copy & paste - able.

When the same is done in Dokuwikis "Code Text" (as in `''ls --all''`), the double-dashes are rendered as "en dash" Unicode character (Hex 0x2013, `&ndash;` in HTML), which makes it unuseable for copy & paste and also prevents users, not aware of this, to get any use of technical documentation, containing these lines.

Dokuwiki's `<code></code>` syntax works fine, but this is not compatible under all circumstances, like together with bullet point - lists (as in `  * <code>ls --all</code>`).

**Comment by mprins** [comment]
I think this may be an artifact of the migration to html5; in the past `''` blocks were rendered using `<tt>` tags which are no longer valid.

IMHO It would be better if DW didn't add the `<code>` semantics to `''` blocks (as it breaks the contract described in https://www.dokuwiki.org/wiki:syntax#basic_text_formatting), and stuck to using a formatting only `<span class="tt">`
Also the `<code>` tag doesn't produce a code block, but produces a preformatted section, loosing the semantics. (example below), so it doesn't work fine.

```
==== test ====
some txt.
  * 1st item
  * <code>ls --l</code>
  * another item
```

is rendererd as

```html
<div class="level3">

<p>
some txt.
</p>
<ul>
<li class="level1"><div class="li"> 1st item</div>
</li>
<li class="level1"><div class="li"> <pre class="code">ls --l</pre>
</div>
</li>
<li class="level1"><div class="li"> another item</div>
</li>
</ul>

</div>
```

see: https://www.dokuwiki.org/sandbox:playground?do=edit

**Comment by The-Judge** [comment]
I didn't meant that all `<code>` semantics should be added to `''`; I did only mention `<code>` as a working example for this single rendering-issue.

**Comment by selfthinker** [comment]
We had this discussion in the past. Previsously raised bug reports were always closed with "Not a bug". See [FS#514](https://bugs.dokuwiki.org/index.php?do=details&task_id=514), [FS#2934](https://bugs.dokuwiki.org/index.php?do=details&task_id=2934), [FS#2882](https://bugs.dokuwiki.org/index.php?do=details&task_id=2882), [FS#2853](https://bugs.dokuwiki.org/index.php?do=details&task_id=2853) and [FS#2853](https://bugs.dokuwiki.org/index.php?do=details&task_id=1128). The "fix" back then was to rename "code" to "monospaced" (but leave `<code>` in the markup).
Because of disagreements in the development team I had created the [UnformattedCode Plugin](https://www.dokuwiki.org/plugin:unformattedcode) to fix exactly that shortcoming. I would like that behaviour to be the default, but at least there's a plugin for it.
