### ISSUE TITLE
Register action will always report a backend failure as "a user with this login already exists"

### ISSUE THREAD

**Issue by ptbrown** [splitbrain/dokuwiki#1093]
The `register` function of [inc/auth.php](https://github.com/splitbrain/dokuwiki/blob/master/inc/auth.php#L1009) calls the plugin method `triggerUserMod`. The backend may be unable to create the user for any reason: a database failure, a name conflict, or (what I'm trying to do) because the password doesn't pass a security test. Yet the reported reason will always be "a user with this login already exists".

Plugins have more information about the reason for failure and thus should be responsible for reporting messages. At leas this one message is too specific for where it's being used. I'm not sure what should be done with the other places where `triggerUserMod` is called, whether to continue to display a possible redundant message or leave all error reporting to the plugin. Should there be a way to silence messages?

**Comment by splitbrain** [comment]
Yeah I think it makes sense that the plugin is responsible for sending the appropriate message. To avoid having no message at all (because the plugin does not send a message) we could print a generic message "User account was not created". So for example in your case the end user would get two messages:

* "Password failed the security check" (this comes from the plugin)
* "User account was not created" (this comes from the register() function

Can you create a PR?

**Comment by ptbrown** [comment]
Done. I see an opportunity to rewrite the two step delete-then-append with a single `io_replaceInFile` function. I'll make another PR for that.
