### ISSUE TITLE
Most templates' layout broken

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki#1131]
#982 introduced a layout issue with nearly 3/4 of templates.

All the templates with old style RTL styles (86 out of 117 templates I have installed on my local machine, i.e. over 73%) have their layout broken as the RTL styles are loaded by default.

One fix could be to only allow valid media types (aural, braille, embossed, handheld, print, projection, screen, speech, tty, tv).
But as the original changes fail to add any `@media` syntax per non-default media type, fixing that could fix this issue as well, although it would introduce invalid CSS (`@media rtl {}`).

**Comment by gamma** [comment]
I agree, this is now a bug. The question is: should this still be supported since the old rtl way has been deprecated a while ago?

As outlined in #982:

#982 is partly ineffective without #1002 which introduces the media type handling (and #1003 which allows multiple media types for the same style file) and also introduces an event for JS modifications and respective caching which should also allow caching for different templates as #1130 intends (maybe not as effective?!)

Anyway, the situation seems a bit complicated to me. How can we proceed? I wonder: do no unit tests exist to ensure compatibility (maybe I should have attached some with this pull request...)

**Comment by selfthinker** [comment]
Especially as #982 is ineffective without any further changes, I would suggest to revert it and make it part of #1002 instead and then fix #1002.

**Comment by selfthinker** [comment]
BTW, the main template I am testing with is Vector (but many others would show the issue as well). But as Vector is the most popular among the non-bundled templates, it makes generally sense to test all sorts of things with it.

**Comment by selfthinker** [comment]
> The question is: should this still be supported since the old rtl way has been deprecated a while ago?

I don't think that's the question as a) so many templates are affected and b) the main problem is the arbitration, which means that even invalid media types like `foo` and `bar` would be allowed.

**Comment by gamma** [comment]
You are absolutely right. My goal with the PRs was to get better control over CSS creation. Adding more options to template and plugin developers. The current state of the CSS and JS file creation is very static. My PRs allowed to inject or remove certain styles and even allow css/less files to be re-used. This is what I basically like to see.

I think it would be nice to leave #982 as is - or revert and supplement it with a whitelist for the suggested media types so that the will have their ``media <> {}`` sections (maybe be using at parts of #1002). Unknown types could be merged into screen. That would solve the RTL thing, but leave the system open for developers to interact with the other definitions when needed.

**Comment by selfthinker** [comment]
I think a whitelist would work well.
But unknown types should not be merged into the screen type as that would not solve anything. It would only move the `rtl` (and potentially `foo` and `bar`) media types from `all` into `screen`. Unknown types need to be completely dropped.

**Comment by gamma** [comment]
How about: unknown types get dropped. Using #1002 authors could change the mediatype from a self referenced one (so they know where it comes from) to a whitelisted one?

**Comment by selfthinker** [comment]
Is there any progress on this?
We should fix it soon as there will be a new release soon.

**Comment by splitbrain** [comment]
I'd like to have this fixed as soon as possible. Could one of you outline the basic steps that have to be done? (I'm having trouble follow the whole discussion)

**Comment by gamma** [comment]
I'd be ok to remove the function and revert to the previous version for sanity of a DW release. #982 should then be incorporated in #1002 or a new PR.

**Comment by splitbrain** [comment]
Okay, I reverted the commit from #982

**Comment by selfthinker** [comment]
As the commit was reverted, this is fixed and can be closed now.
