### ISSUE TITLE
AUTHAD cant get AD Group Membership information for ACL

### ISSUE THREAD

**Issue by ghost** [splitbrain/dokuwiki#1333]
Hello DokuWiki Community,
High Andi !

I am running DokuWiki Release 2015-08-10a "Detritus" on a SLES 11sp3 with Apache using ACLs and "local DokuWiki Accounts" and DokuWiki Groups for some years now. Runs very well! But Today i would like to attach it to our Active Directory Domain "ad" , so we dont need local account registration and grouping any longer. 

I searched the Web and Forums up and down for a solution to my problem, without luck. it seems my DokuWiki is able to authenticate against AD but is unable to fetch the proper group memberships. And because our Wiki is "closed" to unregistred and "groupless accounts" all the AD Users that try to authenticate cannot see any page but the login page (denied.txt) .

I added a "&do=check" to the URL to see some debuging info, but it just proofs that it does not see any group membership. Here is the Output:

```
More than 32MB RAM (134217728 bytes) available.
Changelog is writable
conf directory is writable
mb_string extension is available and will be used
Your locale C seems not to be a UTF-8 locale, you should fix this if you encounter problems.
Debugging support is disabled
You are currently logged in as adm-axel (adm-axel)
You are part of the groups 
Your current permission for this page is 0
The current page is writable by the webserver
The current page is not writable by you
The search index seems to be working
```

My Configuration looks like this:

For a "smooth" transition i added the Chained authentication plugin so i can chain the "authad" plugin with the "authplain" authentication module. Goal is that i can keep my local dokuWiki Accounts while providing parallel the AD authentication. so there is a chance that there are "same sounding" user accounts (say awerner (local) and awerner (AD)) that are of different source and different group membership. but i guess that is not the problem yet, since i also tried "authad" only and didnt changed a thing.

```
<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: FuzzAdmin
 * Date: Fri, 21 Aug 2015 10:43:21 +0000
 */

$conf['title'] = 'FUZZ INTRAnet';
$conf['template'] = 'fuzz2015';
$conf['license'] = '';
$conf['recent'] = 100;
$conf['recent_days'] = 30;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['showuseras'] = 'email_link';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['authtype'] = 'authchained';
// $conf['authtype'] = 'authad'; // does not work either.
$conf['superuser'] = '@admin';
$conf['indexdelay'] = 60*60*4;
$conf['mailguard'] = 'none';
$conf['htmlok'] = 1;
$conf['im_convert'] = '/usr/bin/convert';
$conf['subscribers'] = 1;
$conf['registernotify'] = 'fuzz-admins@fuzz.de';
$conf['mailfrom'] = 'FUZZ-INTRAnet@fuzz.de';
$conf['updatecheck'] = 0;
$conf['plugin']['anewssystem']['d_format'] = 'Y-m-d';
$conf['plugin']['anewssystem']['soapp'] = 1;
$conf['plugin']['anewssystem']['convert'] = '';
$conf['plugin']['authad']['account_suffix'] = '@ad.fuzz.de';
$conf['plugin']['authad']['base_dn'] = 'DC=ad,DC=fuzz.de,DC=de';
$conf['plugin']['authad']['domain_controllers'] = 'ukl-dc01.ad.fuzz.de,ukl-dc02.ad.fuzz.de';
$conf['plugin']['authad']['admin_username'] = 'someAdLoginname'; // not an "AD Admin", but a proper AD Account with sufficient Rights to read others Group-Memberships.
$conf['plugin']['authad']['admin_password'] = 'someAdPassword';
$conf['plugin']['authad']['real_primarygroup'] = 1;
$conf['plugin']['authad']['debug'] = 1;
$conf['plugin']['nssearch']['namespaces'] = '@base';
$conf['plugin']['authchained']['authtypes'] = 'authad:authplain';
$conf['plugin']['authad']['recursive_groups'] = '1';
// end auto-generated content
```

My ACLs look like this:

```
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 18 Jan 2010 13:19:17 +0100
*       @ALL    0
*       @user   0
*       @fuzzall 8
awf:*   @awf    16
awf:*   @fuzzall 1
awf:*   @user   0
awf:*   @ALL    0
gs:*    @gs     16
gs:*    @fuzzall 1
gs:*    @user   0
gs:*    @ALL    0
it:*    @it     16
it:*    @ALL    1
it:*    @user   1
it:*    @fuzzall 1
pk:*    @pk     16
pk:*    @mo     16
pk:*    @fuzzall 2
pk:*    @ALL    0
pk:*    @user   0
qs:*    @fuzzall 1
start   @newseditor     2
start   @fuzzall 2
start   @ALL    0
*       @rol%2dorg%2dfuzz       8
start   @rol%2dorg%2dfuzz       2
```

There you can see all my old and well working ACLs including the local Groups (local to DokuWiki) and the last two lines are a try to add permissions to an AD Group called "rol-org-fuzz" which contains all my users of the organisation. 

no success so far.
Any Idea what the hell im doing wrong here ?!?
Thanks in advance for any help that gets this baby flying!!!

best wishes and greets
Axel

**Comment by splitbrain** [comment]
some things to try:

enable debugging in DokuWiki core - errors might not be printed otherwise

get rid of chained auth to make sure it's not interfering

use a real AD admin just to make sure it's not a permission problem on the
AD side

check the event log on the AD server

**Comment by axel1973** [comment]
DokuWiki Core debugging enabled. >> still no error messages, except if there is nothing (or fake) account information entered at the "AdAdmin Account + Passwd". 

As mentioned in the config example, it does not matter if authchain or authad alone. its just the same. but for you i am going to test this again with "authad" only soon. (in this mode im unable to gain access to the admin or config pages any longer, since the ad account i authenticate with is not part of the superuser/local admin group on the wiki. 

Also i called the real AD Administrator to enter his account data for the AdAdmin+Pass and have a look with me on the Windows Logs of the DC. BUT the AD Admin said that common AD User's Permissions are "sufficient" to read any Users Group-Membership from the AD. He said he tested it with some LDAP Client on the AD DC.  So.... :/ yeah.   Will report back soon if we could test with REAL AD ADMIN Account. 

Axel

**Comment by axel1973** [comment]
OMG! We solved the problem. Now to Documentation and Feedback purposes, here is my solution to my problem:

1.
a simple AD Account is mostly sufficient to be used with the 
    $conf['plugin']['authad']['admin_username'] = 'someGenericAdLoginname'; // not an "AD Admin", but a proper AD Account with sufficient Rights to read others Group-Memberships.
    $conf['plugin']['authad']['admin_password'] = 'itsAdPassword';

2.
most Important and the core of the problem i had where found at this Block:
    $conf['plugin']['authad']['account_suffix'] = '@ad.fuzz.de';
    $conf['plugin']['authad']['base_dn'] = 'DC=ad,DC=fuzz.de,DC=de';

Can you see it ?

Its the wrong base_dn String. Its supposed to be 
    $conf['plugin']['authad']['base_dn'] = 'DC=ad,DC=fuzz,DC=de';

Since this String was handed to me by the AD Admin i assumed to be correct and did not questioned it as faulty. That fixed the problem.  Anything else (like authchain and acls) been good. 

I hope my feedback of my mistake will help others that trip over the same mistake on their approach to connect DokuWiki to an active directory. 

CASE CLOSED.

To Andi and all the others who contributed to DokuWiki: THANK YOU for this wonderfull piece of free Software!!

best wishes
Axel

**Comment by axel1973** [comment]
im done

**Comment by splitbrain** [comment]
Ahhh I should have seen that. But didn't notice. Good that you figured it out.

**Comment by axel1973** [comment]
I recommend to add a error or debug message that points to a possibly wrong
base_dn whenever absolutely null groups are returned. That's most likely a
mistake, since an ad user is always in some groups

**Comment by nenych** [comment]
Hello. I have the same issue with 2018 release.
My config:
$conf['title'] = 'Wiki';
$conf['template'] = 'monobook';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['authtype']       = 'authchained';
$conf['superuser'] = '@admin';
#$conf['superuser'] = '@wiki_administrators';
#$conf['superuser'] = 'mykhailo.nenych';
#$conf['disableactions'] = 'register';

$conf['plugin']['authad']['account_suffix'] = '@some_company.com';
$conf['plugin']['authad']['base_dn'] = 'dc=central,dc=co,dc=some_company,dc=com';
$conf['plugin']['authad']['domain_controllers'] = 'dc-kiev0.central.co.some_company.com';
$conf['plugin']['authad']['admin_username']        = 'wiki.srv';
$conf['plugin']['authad']['admin_password']        = 'pass';
$conf['plugin']['authad']['sso']                = 1;
$conf['plugin']['authad']['real_primarygroup']  = 1;
$conf['plugin']['authad']['use_ssl']            = 1; // Don't have ssl/tls options enabled at the same time. 
$conf['plugin']['authad']['use_tls']            = 1; // Only one of them.
$conf['plugin']['authad']['debug']              = 1;
$conf['plugin']['authad']['ad_port'] = 636;
$conf['plugin']['authad']['recursive_groups']   = 1;

$conf['plugin']['authchained']['authtypes'] = 'authad:authplain';
$conf['plugin']['authchained']['usermanager_authtype'] = 'authad';

I can login with AD, and i see my groups in user manager:
wiki_administrators, vpn.checkpoint, lapsnopassaccess, ...

My ACL:
*       @ALL    1
*       @user   8
*       @wiki%5fadministrators  4

and i can only read by first rule when i logged in as domain user.

Please help me to solve this problem

**Comment by nenych** [comment]
I discovered that users from directory Admins works perfect, but users from directory Users does'nt.
My structure:
central.co.some_company.com
----Some_company
--------Branches
------------Cities ...
------------Kiev
----------------Admins                (works perfect)
----------------Folders ...
----------------Users                  (Does not word. Can log in but groups as described in previous comment)
--------Another folders ...

**Comment by phy25** [comment]
I am closing this because unfortunately we delegate these to AuthAD library, which encapsulates this process with no way to see what path they are actually querying. Except switching to another library, I don't think we can do anything about this.

*(notice the `@` before `$this->info()`)*

https://github.com/splitbrain/dokuwiki/blob/f17724f821884e579f5b6eb846ed95c7d5b15eeb/lib/plugins/authad/adLDAP/classes/adLDAPUsers.php#L195
