### ISSUE TITLE
ACL is not enforced for sidebar

### ISSUE THREAD

**Issue by 8191** [splitbrain/dokuwiki#1369]
The sidebar is shown even if a user does not have "Read" rights for the sidebar page.
In my understanding of the Dokuwiki ACLs, the sidebar should be hidden if the current user has set the rights "None" for the sidebar page or any parent namespace the sidebar page resides in.

**Comment by michitux** [comment]
I think this is a bug or at least unexpected behavior and should be fixed. Imagine a scenario where you have a global, public sidebar and a private namespace with a private sidebar with possibly internal content (e.g. `:sidebar` and `internal:sidebar`). I think sidebars the user cannot access should simply be ignored. Therefore I propose to change `page_findnearest()` to (optionally?) ignore any page the current user cannot access. I would even suggest to change its default behaviour but provide a parameter to turn it off in order to fix **all** templates that are using it but still provide a possibility to override the check in order to allow other usages.

**Comment by splitbrain** [comment]
makes sense to me

**Comment by 8191** [comment]
> Imagine a scenario where you have a global, public sidebar and a private namespace with a private sidebar with possibly internal content
That's how I recognized it... ;)

In my option it's not required to make the behavior optional, since one can simply change the ACLs of the sidebar page to "Read" for @ALL. But I'd say that depends on the Dokuwiki Team's view on backwards compatibility.

**Comment by Chris--S** [comment]
I don't think there should be any option.  Like @8191 says, ACL can be used to configure page visibility to users.  Expected behaviour is inaccessible content is inaccessible, template authors shouldn't be able to override this.

**Comment by michitux** [comment]
I was suggesting to add a parameter like `$ignoreacl` to `page_findnearest` (not in the template or for users) so this function could also be used for other purposes outside of any template where ACLs might not play any role. However I don't know such a purpose so might as well not add a parameter.

**Comment by michitux** [comment]
I've just opened #1370 with a possible fix with parameter, feel free to remove it if you think it is not necessary. I have not tested this in a real wiki, just with this test case, so please test this change if possible.

**Comment by 8191** [comment]
#1370 Works for me as expected.
