### ISSUE TITLE
No email subscriptions when using authphpbb3

### ISSUE THREAD

**Issue by amulheirn** [splitbrain/dokuwiki#1449]
I am having trouble with email subscriptions.  (See also https://forum.dokuwiki.org/thread/13322) 

When using authphpbb3 as the authentication backend, email subscriptions do not get sent.   However, when 'signing' a wiki entry, Dokuwiki *does* know the user's email address, so there is obviously not a problem reading this information from the phpBB forum.

When I use authplain, email subscriptions work ok.

I am unsure if this is a Dokuwiki problem or an authphpBB3 problem.   If you can advise and (if necessary) close this bug that would be much appreciated.

**Comment by splitbrain** [comment]
There's a difference between having the current user's email (which is what happens when you sign something) and the need to have access to arbitrary user's email addresses during notification. However, this should be reported to the authBB plugin author.

**Comment by Goldenmenu** [comment]
I am not sure if my comment will be revelant but I had the same issue for a while with almost same setup (authAD) and I just figured out why. 

After reading your previous comments here and on https://forum.dokuwiki.org/thread/13322 , I assumed the problem came from the authentification. Actually, I didn't fill the **plugin»authad»admin_username** and **plugin»authad»admin_password** settings (while it's clearly said you need those settings for email subscriptions). 

Filled with proper credentials, emails from Subscriptions work fine ("notify" emails worked before as well). 

I hope, it will help someone with same issue.
