### ISSUE TITLE
AUTHAD group membership empty when samaccountname != userprincipalname

### ISSUE THREAD

**Issue by mghie** [splitbrain/dokuwiki#1465]
Hi,

I have a problem with AD integration using DokuWiki on Debian 8. When I login as a user where `samaccountname` is the same as `userprincipalname` excluding the domain part (using the full `userprincipalname` as my user name in DokuWiki) then I get the following data:

> DokuWiki version: Release 2014-05-05a "Ponder Stibbons"
PHP version 5.6.17-0+deb8u1
More than 32MB RAM (134217728 bytes) available.
Changelog is writable
conf directory is not writable
mb_string extension is available and will be used
Your locale C seems not to be a UTF-8 locale, you should fix this if you encounter problems.
Debugging support is enabled. If you don't need it you should set $conf['allowdebug'] = 0
You are currently logged in as mh-admin (Hieke, Michael (Admin))
You are part of the groups domänen-admins, domain_users, user
Your current permission for this page is 255
The current page is writable by the webserver
The current page is writable by you
The search index seems to be working

which looks OK to me. If however I login with another account where the two values differ, then I don't get any group membership returned, and editing is therefore disabled:

> You are currently logged in as michael.hieke (michael.hieke)
You are part of the groups
Your current permission for this page is 1
The current page is writable by the webserver
The current page is not writable by you

The `samaccountname` is `mh`, the `userprincipalname` is `michael.hieke@my.domain`. The domain name itself is `internal.my.domain`.

Is there any configuration setting that I need to set (Google searches have so far not resulted in anything helpful), or is there a bug somewhere?

**Comment by splitbrain** [comment]
From a quick look at the source code it seems adldap 4.0.4 uses the samaccountname to look up group memberships. The way groups are looked up changed in the current devel version (https://github.com/adldap/adLDAP) changed the way groups are looked up. However the new version is still in development and has not been released, yet. It might be worth to submit a bug report at the adldap bugtracker, but it might not get fixed before 5.0 is out.

When adldap 5.0 is available, the authad plugin could be updated to use it, but it would require some rewriting since the API changed. Switching to 5.0 would increase the required PHP version to 5.4.
