### ISSUE TITLE
$returnonly parameter is missing in Doku_Renderer declarations

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#1466]
Some time ago the parameter ```$returnonly``` was introduced to the link functions in the XHTML renderer. This has also been implemented in the ODT renderer of the ODT plugin.

In phpunit I keep on getting php strict warnings because the declaration of some functions does not match to the Doku_Renderer class. I get the warnings for ```camelcaselink()``` and ```emaillink()```.

Is ```$returnonly``` a part of every renderer? It would be nice if its included in the declarations of Doku_Renderer base class to get rid of the warnings.

**Comment by splitbrain** [comment]
I experimented a bit with PHP7's new signature checking for descendant class methods. It seems it is okay for child classes to extend the parameter list of an overriden method as long as those additional parameters are optional.

See http://commie.io/#CZfJdOc0 for a very simple test case. PHP7 will only print a warning for class b but is fine with class c.

The additional returnonly parameters introduced in the XHTML renderer are optional (that's why we don't get any errors in our own test suite).

So, to answer your initial question: the $returnonly is not part of every renderer (for some renderers with complex internal document structure it might not even possible to return a single element without the document context).

The question that remains is why you get errors. Your $returnonly parameter should be optional and thus shouldn't show any errors. Can you give us the exact error message?

**Comment by LarsGit223** [comment]
Sorry, my description is misleading. I do not get errors as a test result but PHP strict messages during test execution, e.g.:

```PHP Strict Standards:  Declaration of renderer_plugin_odt_page::camelcaselink() should be compatible with Doku_Renderer::camelcaselink($link) in /home/lars/public-html/dokuwiki/lib/plugins/odt/renderer/page.php on line 4404```

I am not on PHP7 yet because Ubuntu is not delivering it yet. Do you think updating might make the message disappear?

**Comment by splitbrain** [comment]
I assume this problem has been solved with https://github.com/LarsGit223/dokuwiki-plugin-odt/pull/138

**Comment by LarsGit223** [comment]
Yes, thanks again.
