### ISSUE TITLE
Sitemap (&do=index) does not consider $config["useheading"]

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#1499]
The sitemap created by the &do=index URLs does not respect $config["useheading"].  When this setting is on (1), the index should use the page headings of the respective namespace default page (also following https://www.dokuwiki.org/namespaces#namespace_default_linking) instead of bare directory names for namespaces.  This is currently - Release 2015-08-10a "Detritus" - not the case.  Namespace default files are currently listed as regular files within the namespaces, which is confusing for many users.

**Comment by micgro42** [comment]
That is correct, because the sitemap is a sitemap and not a navigation. To quote [wikipedia](https://en.wikipedia.org/wiki/Site_map):
> A site map (or sitemap) is a list of pages of a web site accessible to crawlers or users. It can be either a document in any form used as a planning tool for Web design, or a Web page that lists the pages on a Web site, typically organized in hierarchical fashion.

There are plugins available that are designed to provide a navigation, like [simplenavi](https://www.dokuwiki.org/plugin:simplenavi) or [indexmenu](https://www.dokuwiki.org/plugin:indexmenu). These plugins respect $config["useheading"]  and the latter can optionally also replace the index.

**Comment by fthommen** [comment]
OK, I note that. I wasn't aware of this definition of the term "sitemap" as usually sitemaps on websites _are_ provided for navigation. So a "fix" could be to disable the sitemap completely to avoid user confusion.

**Comment by splitbrain** [comment]
The sitemap is meant to give the user an idea about the structure of the whole site. Showing the real namespace structure is important to gain that understanding.
