### ISSUE TITLE
msg() drops duplicate messages in core

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#1601]
When ```msg()``` is called multiple times with the same content, it is only displayed once.

Steps to reproduce:

1  Add two ```msg()```-calls to inc/handler.php around line 1377:
```php
case 'tablecell_open':
case 'tableheader_open':
    msg('foo');
    msg('open ' . $lastCell);
    $lastCell++;
    $cellKey[$lastRow][$lastCell] = $key;
    break;
```
2 Open a wikipage with tables
3 Note that ```foo``` is only displayed once, but ```open ``` + number is displayed once for every cell

However I could not reproduce this behavior when I called ```msg('bar')``` in a plugin helper. Then the identical message was printed repeatedly as expected.

cc @splitbrain

**Comment by michitux** [comment]
This is expected behaviour when the messages are generated before the output starts. After the output started, messages will be displayed again. I remember this is to prevent duplicate messages when messages are saved in the session and then the same message is generated again e.g. after a redirect. The code is in `inc/html.php` in `html_msgarea()`.

**Comment by splitbrain** [comment]
ah, so that's where it was hiding :-) makes sense. thanks for the reminder
