### ISSUE TITLE
Move all template texts to lang.php, but keep the support of templates

### ISSUE THREAD

**Issue by furun** [splitbrain/dokuwiki#1635]
This is only a suggestion for a discussion, not a real issue.
(kind of related to #1101)

Could it be useful to move all texts in lang/../*.txt in to lang.php files?

All Texts could be constructed in code instead of a template text file.
And a template file still could be used for custom changes. It would be used if it exists. (examples included in dw pack)
And complex texts in templates could be composed with @LANG_@ placeholders.

=== Example for password.txt:
```
Hi @FULLNAME@!

Here is your userdata for @TITLE@ at @DOKUWIKIURL@

Login    : @LOGIN@
Password : @PASSWORD@
```

=== To password.txt:
```
@LANG_welcome_name@

@LANG_here_your_userdata_login@

@LANG_login@    : @LOGIN@
@LANG_password@ : @PASSWORD@
``` 

=== In lang.php
```
login = "Login"
password = "Password"
welcome_name = "Hi @FULLNAME@!"
...
```
=== In Code

`GetTemplateText_password($language=null) { ... use code or template-file if exists ... }`
 or 
`GetTemplateText_password($language=null) { ... use dw  template-file or custom template-file if exists ... }`
 or 
`GetTemplateText($file, $language=null) { ... use dw  template-file or custom template-file if exists ... }`

===

Good:
- It would drastically reduce the amount of files in dw. Each language hast over 30 template files. Many of them with only simple text.
- Download with language selection is not needed then anymore.
- Central management of all texts, easier for translations.
- All texts have the same formats in any language.
- Easy expendable, because only a little code and 1 template file has to be modified, if DW or user want a change.
- Users change texts maybe preferable in a custom lang.php instead of a template, and still could use templates if they like.
- A custom template could be a HTML file with @LANG_@ and @info@ placeholders.

Bad:
- The lang.php files would be bigger.
- Long texts in lang.php maybe with Paragraphs.
- The change is work intensive. Little tool code can do the process. But lang templates are messy and must be manually checked.
- Some helper code have to modify things like even space in blocks of "@LANG_...@ : @...@" informations.
- It gets a little more complex, but i think not much, and easy for users which are willing to spend time for custom.

**Comment by splitbrain** [comment]
Sorry, that doesn't make any sense to me.

I'll answer your points in order:

"good":

* why is having less files good?
* amount of language specific code (filesize) would be the same, people might still want to omit it and it's already implemented
* we already have central translation management at translate.dokuwiki.org
* how would texts have the same format in any other way than they currently have?
* I don't understand
* why would users prefer editing PHP code instead of the wiki syntax they already know?
* generalized LANG_ placeholders might be interesting but would rarely be needed

bad:

* much bigger
* much harder to read and to debug. a PITA to merge
* lot's of work for no benefit
* yeah layouting plain text would be a pain
* nobody needs more complexity
