### ISSUE TITLE
One click delete for managers

### ISSUE THREAD

**Issue by SonoDavid** [splitbrain/dokuwiki#1669]
A consequential addition to the one click revert for managers (http://dev.splitbrain.org/darcsweb/darcsweb.cgi?r=dokuwiki;a=commit;h=20090911081833-7ad00-5a64feb7e3e1b37178295c290a6c97c3923e82e3.gz) would be the one click _delete_ for managers.

In git: https://github.com/splitbrain/dokuwiki/commit/1246e01639ddb1343de1532a6a46182c4137ca7a

**Comment by Klap-in** [comment]
Why specific for wiki managers, and not for all wiki users?

Wiki managers already know how to delete a page, while (relative new) wiki users are more often wondering how to perform that.

**Comment by SonoDavid** [comment]
It could be for all users, but then there should be added control for this using the ACL management module. Nobody wants a random visitor deleting the pages on your wiki, right?

**Comment by Klap-in** [comment]
This button would not more than just a shortcut for something that is already possible!

With respect to permission levels (https://www.dokuwiki.org/acl#background_info):
for pages the permission levels are:
- no permission
- read permission
- edit permission

If someone can edit, he/she can also just delete all text in editor window and save. That is of course also editing. Actually that is current THE way to delete a page.

Because for people not familiar to the wiki it not always that obvious that to delete a page, you have just to delete all its wiki text, it could be worth considering if a delete button would be useful. 

btw:
Another way for offering this feature is as plugin, something similar to the [addnewpage](https://www.dokuwiki.org/plugin:addnewpage) Plugin, which add small form to wiki interface for adding new pages.)

**Comment by SonoDavid** [comment]
Indeed, I want something similar to the [pagemove](https://www.dokuwiki.org/plugin:pagemove) plugin, which adds an extra button to the dokuwiki interface so the page can be easily moved. You can of course move (or delete) a page in many different ways, but I find the plugin functionality very intuitive.

**Comment by selfthinker** [comment]
The reason why [the original bug report](https://bugs.dokuwiki.org/index.php?do=details&task_id=1789) asked to have this only for managers is because the revert button is also only available for managers. I guess there are pros and cons for both, but if you wanted to have a delete button for everyone, then to be consistent the revert button should also be available for everyone.

**Comment by molefunk** [comment]
https://www.dokuwiki.org/plugin:deletepagebutton
