### ISSUE TITLE
File with name jump4.png is falsely recognized as video

### ISSUE THREAD

**Issue by wmertens** [splitbrain/dokuwiki#1701]
When trying to embed an image called `jump4.png`, the resulting page shows an error about it not being a video, because it sees the `mp4` in it as being the `.mp4` extension.

This is wrong for 2 reasons:
* it should recognize only a dot followed by `mp4`
* it should only use the last part of the URL query or path, in that order

So these should be .jpg files: `foo.mp4.thumb.jpg` and `foomp4.php?getThumb&.jpg`

**Comment by selfthinker** [comment]
I cannot reproduce this. I uploaded a file I previously renamed to exactly "jump4.png" and had no issues embedding it.
What was the exact syntax you used? And which DokuWiki version was it?

**Comment by wmertens** [comment]
I don't know the version, I'm asking around. The wiki page that had the problem is at http://waytools.rocks/keyboards/jumps/start - It doesn't seem to have a history feature?

Anyway the syntax used was `|  {{jump4.png?550}}  |`, I tried renaming the file but could not find out how so uploaded a new one and used `|  {{jump_4.jpg?550}}  |` which works.

**Comment by selfthinker** [comment]
I was just able to reproduce it by installing the [html5video2 plugin](https://www.dokuwiki.org/plugin:html5video2) that you use on your website. So, the bug is in there and should be reported in [their issue tracker](https://github.com/lisps/html5video/issues).
By the way, you don't need that plugin as DokuWiki supports videos out of the box. The only thing that plugin gives you is a flash fallback (which you might or might not need).

**Comment by wmertens** [comment]
@selfthinker Thank you very much for your help!
