### ISSUE TITLE
SSRF vulnerability in Dokuwiki

### ISSUE THREAD

**Issue by ambulong** [splitbrain/dokuwiki#1708]
Hi, 
I found a ssrf vulnerability in dokuwiki. The sendRequest method in HTTPClient Class(In file: /inc/HTTPClient.php) has no restrict to access private network, such as, 10.0.0.1/8, 172.16.0.0/12, 192.168.0.0/16. This allows user to scan port of internal network.

For example, 
1. edit any page in dokuwiki
2. Input `ssrf{{http://127.0.0.1/log.php?ssrftest.png?recache|}}`
3. Hit preview

And the server will send a request to 127.0.0.1, we can detect the port is open or not according to the response time.

Hongkun Zeng
hongkun.zeng@dbappsecurity.com.cn

**Comment by michitux** [comment]
As DokuWiki installations are also used in internal networks where this might be desirable, simply disabling this altogether might not be good for everybody. Still it is a problem as the source ip address might give access that would otherwise be denied. Maybe adding a setting to allow such requests that is disabled by default could be a solution? I'm also not sure if this is really an issue for images (as they are not cached/fetched by default), but it probably is an issue for RSS feeds.

**Comment by ambulong** [comment]
Yes. I think DokuWiki should be disabled to access private network by default. It can refer to the wp_http_validate_url() method in WordPress.
https://github.com/WordPress/WordPress/blob/master/wp-includes/http.php

**Comment by ambulong** [comment]
CVE-2016-7964

**Comment by michitux** [comment]
I think for properly fixing this vulnerability, the solution is not to disallow local requests, but the solution is to make sure DokuWiki isn't doing **any** requests to hosts other than dokuwiki.org by default. The reason is that as it is e.g. explained [here](https://cwe.mitre.org/data/definitions/918.html), SSRF is not only a problem with local addresses, but actually with any address. Note that also non-local IP addresses might be behind firewalls that e.g. allow certain IP ranges. For examples in a university network, usually no private IP addresses are used (as there are enough public IP addresses available), but there are still private file servers, databases, ... that are only reachable internally.

Note that, as far as I can see, the example mentioned in the initial report does **not** work with a default configuration, as by default no media file is fetched. We should probably add an additional warning to the [fetchsize](https://www.dokuwiki.org/config:fetchsize) option which enables this though.
As I've already commented above, I think the RSS/feed embedding feature is the main "problem". While adding a configuration option to disable local IP addresses might help, this won't fix the problem. Therefore I guess we need to disable the feed feature by default and add configuration option with an appropriate warning that allows to enable it, maybe with an option to only allow non-local ip addresses. Any thoughts on this?

**Comment by splitbrain** [comment]
The only way I see to properly fix this is to add a whitelist feature where an Admin can define the external hosts and IPs the wiki is allowed to contact. However for not breaking every already installed wiki we would need to keep this list empty (allowing all).
TBH I feel like it's not our task to secure other computers. If a wiki server runs within a network that should not be reached from that wiki server, the wiki server should be isolated properly through at least outgoing firewall rules or by a proper DMZ setup.
