### ISSUE TITLE
Username enumeration from Reset Password Feature

### ISSUE THREAD

**Issue by erwanlr** [splitbrain/dokuwiki#1727]
Hi There,

The reset password feature allow attackers to gather a list of valid usernames by checking the response. Such data could then be used in password attacks against the wiki.

When submitting an unknown username: "Sorry, we can't find this user in our database."
With a valid username:  "A confirmation link has been sent by email." & Login form displayed

Both responses should be with a generic message and not disclosing the existence (or not) of the username submitted.

Furthermore, could it be possible to trigger an event in the act_resendpwd() in order to be able to log & block such attempts ? (or is there a way to do it that I missed ?)

**Comment by splitbrain** [comment]
This is an recurring discussion for every service there I guess. The thing is, that it is extremely unhelpful for legitimate users not knowing if their password reset succeeded or not (because they might need to try multiple possible user names).

Here's an example of such a discussion for the Discourse forum software: https://meta.discourse.org/t/different-password-reset-for-wrong-username-email/15909/22

Regarding the event, if there's none please feel free to send a PR adding one.
