### ISSUE TITLE
ACL: actual rights differ from rights shown in admin panel when users are in multiple groups

### ISSUE THREAD

**Issue by LeSpocky** [splitbrain/dokuwiki#1750]
On http://www.netz39.de/wiki we have some behavior I wouldn't expect and which I could reproduce with a fresh install of Release 2016-06-26a "Elenor of Tsort" at http://www.lespocky.de/test/dokuwiki/ so let me explain (with the names used in the test wiki).

We have two groups called _board_ and _members_. Usual users are in the _members_ group, but some are additionally in the _board_ group. So some users are only in one group and some are in both groups.

Now we a namespace _board:*_ which should not be accessible for not logged in users at all. Users which are in the group _board_ should be able to read and edit all things in this namespace. There's also another namespace _board:meetings:*_ inside of that, which should be read only by users which are in the group _members_ only (but not in the group _board_). One particular site _board:meetings:next_ should not be readable for those.

I made screenshots of the user list and the current ACL rules:

![dokuwiki_bug_acl_01](https://cloud.githubusercontent.com/assets/661636/20208370/0a9e002e-a7ee-11e6-912f-0a29d9cd20bb.png)
![dokuwiki_bug_acl_02](https://cloud.githubusercontent.com/assets/661636/20208371/0a9ed062-a7ee-11e6-9ecc-ccf0f8bab219.png)

I wrote down what rights I would expect and what actually happens in a table in the test wiki and made another screenshot:

![dokuwiki_bug_acl_03](https://cloud.githubusercontent.com/assets/661636/20208402/3a4f29e2-a7ee-11e6-941b-64e842499ac1.png)

The expected behavior is the same what the admin panel shows me, if I select the namespaces and sites and let me show what the groups can actually do. What really happens is the users in the group _board_ (which are also in the group _members_) can not access sites for which we have explicitly overridden some previously granted rights for the group _members_.

Note: if I create another user, which is in the group _board_, but not in the group _members_, this user has access as expected and shown in the ACL admin area. However, due to other parts in our live wiki (not the test one), we can not have such users.

If you want to have a closer look at http://www.lespocky.de/test/dokuwiki/ you can login as the users shown in the screenshot above using the username as the password.

As a workaround: for the ACL entries we created for the _members_ group we add another explicit rule for the _board_ group which is redundant to the inherited behavior, but gives actual access we want. (I did not cover this in the test wiki).

**Comment by splitbrain** [comment]
Okay this setup is interesting. This is rather hard to evaluate by hand, but let's try anyway.

User ``board``:
* in ``board:*``
  * there two matching entries: line 3 and 4 (because the user is member of group ``@members`` and of ``@ALL``)
  * the higher permission ``Delete`` wins
  * evaluation aborts
  * Result: ``Delete``
* in ``board:meetings:*``
  * there is one match: line 5 (because the user is member of group ``@members``)
  * the line gives ``Read`` permissions
  * evaluation aborts
  * Result: ``Read``
* for ``board:meetings:next``
  * there is one match: line 6 (because the user is member of group ``@members``)
  * evaluation aborts
  * Result: None

User: ``member``
* in ``board:*``
  * there is one matching entry: line 3 (for ``@ALL``)
  * evaluation aborts
  * Result: ``None``
* in ``board:meetings:*``
  * there is one match: line 5 (because the user is member of group ``@members``)
  * the line gives ``Read`` permissions
  * evaluation aborts
  * Result: ``Read``
* for ``board:meetings:next``
  * there is one match: line 6 (because the user is member of group ``@members``)
  * evaluation aborts
  * Result: None

So far this is exactly matching with the results you got.

However you're now wondering why you see different evaluations in the ACL editor. This is because the ACL editor will only evaluate the ACLs for the currently selected group or user. Eg. When you select a group it will only find matches for exactly this group and if you select a user it will only find matches for this user (regardless of what groups they are in).

So from a purely academical standpoint the ACLs seem to be correct. However trying to evaluate this gave me quite the headache, thus I would recommend adjusting your ACLs to make easier for you: just reset the evaluation at a certain level by setting the ``@ALL`` permissions. Those will always apply to everyone and then you can increase permissions from there.

So for your desired permissions, this should do it:

```
board:* @ALL 0
board:* @board 16
board:meetings: @ALL 0
board:meetings: @members 1
board:meetings:next @board 16
board:meetings:next @ALL 0
board:meetings:next @board 16
```

Yes, it introduces a few superfluous lines but makes reading and evaluating it in your head much simpler.

**Comment by LeSpocky** [comment]
Thanks for your investigation. What you describe is basically the workaround we already use:

> As a workaround: for the ACL entries we created for the members group we add another explicit rule for the board group which is redundant to the inherited behavior, but gives actual access we want.

¯\_(ツ)_/¯
