### ISSUE TITLE
Can't download plugin file from github

### ISSUE THREAD

**Issue by Laurent3170** [splitbrain/dokuwiki#1798]
I am trying to update the plugins from https://wikidurable.org but I receive a `Impossible de télécharger le fichier : https://github.com/turnermm/ckgedit/archive/master.zip` (Impossible to download the file...).
The file can be accessed from a normal http connection, so it seems to be a question of access rights on the wiki part, but the folders are 0755 and files 0644 and I haven't change anything since last update (a few weeks ago). Moreover If I try to update wiki I receive `Could not connect to ssl://raw.githubusercontent.com:443 (0)`.

I am using `Release 2016-06-26a "Elenor of Tsort` but don't know where to search nor to find a more explicit message.
Thanks

**Comment by Klap-in** [comment]
The error to webserver log was suppressed by `@` at line 330 in following reference, but subsequently the error output is included in the error message... https://github.com/splitbrain/dokuwiki/blob/65d3a5db1b1c8fa46b1aa39f43ae3598dc6dafb4/inc/HTTPClient.php#L330
(The error string and number is the `(0)` part in message that you posted, however that is not that informative of course.)

**Comment by splitbrain** [comment]
Yeah, that error message is as explicit as it gets. Your PHP's SSL might not be configured correctly (eg. it does not trust the normal certificate chain and thus doesn't trust github's certificate) or some firewall might blocking outgoing connections on your server. Nothing we can do here.

**Comment by Laurent3170** [comment]
Yes, nothing you can't do, but having a more explicit message can be helpful... Because trying to solve with just an "impossible to access" is quite hard.
I think you got the explanation, it might have to deal with my SSL as I have changed of provider.
Thanks

**Comment by Laurent3170** [comment]
Sorry to bother you, but don't know where to ask. It seems that the SSL is well installed https://www.sslshopper.com/ssl-checker.html#hostname=wikidurable.org. I should look at `HTTPClient.php` to try to find where it blocks ?

**Comment by splitbrain** [comment]
That link checks the certificate of *your* website which has absolutely nothing to do with the problem at hand. Your PHP setup needs to trust the certificate of github.com. Check your setup of the CA file or directory http://php.net/manual/en/openssl.configuration.php

**Comment by Klap-in** [comment]
Maybe I deviate a bit too much...bit here are some questions..
- I see the code is writing some additional debug output, but I have no idea were that should appear...who knows?
- From php manual http://nl3.php.net/manual/en/function.fsockopen.php :
"If the value returned in errno is 0 and the function returned FALSE, it is an indication that the error occurred before the connect() call. This is most likely due to a problem initializing the socket."
- ~~says that ssl checker also something about download from hosts using ssl?~~ nope, according reaction of splitbrain 
- is a command line tool like `wget` also using OpenSSL? Maybe that shows bit more info?
