### ISSUE TITLE
Change a users Group sends new password

### ISSUE THREAD

**Issue by Oneboy1979** [splitbrain/dokuwiki#1808]
Hi,

i install DokuWiki on my server without any problem. Now i play a bit around with ACL and registered a new user. The user received an Mail with its Username and Password thats ok.
The user login and change the password.
After that, i add the user to the group editors i do this with the User Manager and check the Notify User checkbox. So the problem is, the user received another e-mail which contains a new generated password.

Can anyone please help me with this?

regards

**Comment by splitbrain** [comment]
When you select the notify option and leave the password field empty a new one is generated. Don't use this option for changing groups. There is no reason to notify a user about a group change. It's not actionable for the user anyway.

**Comment by rgleason** [comment]
So you must notify them by personnal email that their group was changed to editor?  Or send them a message by checking the send email box whick will also send a new  pw . 

The no notice option is interesting but there is no acrtion closure.

**Comment by splitbrain** [comment]
why would you want to inform users about their groups? Users are not interested in their groups. They are interested in their permissions. They want to know that they now can edit X in the wiki. This you have to tell them in another way anyway.

**Comment by rgleason** [comment]
Sorry, mixed up grioups and permissions. 
When I change a user permission to Edit, I must inform them by normal email or their pw will be changed when i check the email box and leave the pw empty? 
I did not realize this. I'll have to look, is there a reminder message near the box for admins?
--I suppose the user could just set it back.Is this caused some security concern?

**Comment by Oneboy1979** [comment]
Ok that is clear now! I miss understood the notify button, I thinked that this informs users also that his group has changed and that he now can edit!

**Comment by rgleason** [comment]
These messages below. the form and   Notify User [checkbox]
1.    New users will be added to the default group (user) if no group is specified.
 2.   The password will be autogenerated if the field is left empty and notification of the user is enabled.

This could not be much clearer.
 
Since we do not have access to the PW (for security), if we want to notify users that they are now in the "Manager" group and can "Edit" the Dokuwiki  {We have had trouble with totally open registration in Druple6] we will just have to send via normal email!  and it's not hard to copy the email.

Sorry.  Hope this is still Closed.
