### ISSUE TITLE
tok bypass and SSRF vulnerability in Dokuwiki

### ISSUE THREAD

**Issue by niubl** [splitbrain/dokuwiki#1883]
the tok of fetch.php can be guess in php version above 5.5:
http://simple.com/dokuwiki/lib/exe/fetch.php?media=http://192.168.141.128:80/test.php?test.jpg&tok=0f35df

and attacker can use this make a SSRF attack,vulnerability detail: 
http://paper.seebug.org/230/

email:
448354223@qq.com

**Comment by splitbrain** [comment]
Could you please submit details in English?

**Comment by splitbrain** [comment]
I'm trying to figure out what's going on via Google Translate, but 'm not sure I'm getting the details, right.

From what I gather, you're saying you can influence what ``media_get_token()`` and ``getSecurityToken()`` return by passing an invalid session ID exploiting a bug in PHP.

You state that ``auth_cookiesalt()`` is using the sessionID to generate the salt, but that isn't true. It uses ``random_bytes()`` and only appends the session ID to that if ``$addsession`` is set to true. It's false for both functions above.

Again, please provide an english description and maybe some example code exploiting the problem (feel free to send sensitive data directly to andi@splitbrain.org)

**Comment by phy25** [comment]
Sad to see this report. Here is some translations to the blog.

DokuWiki `fetch.php` allows downloading external files with url's param `media`. There is a signature check with param `tok`.

`checkFileStatus()` > `media_get_token()` > `auth_cookiesalt()`

The value returned by `auth_cookiesalt()` is joined by the salt in `DokuWiki_htcookiesalt2` and value from `session_id()`. The practice generating salt by using `session_id()` is not safe. There is a bug in `session_id()` in the latest PHP* (older versions are not affected), which may set any value to `session_id()` by the client cookie (For detail please see the original Chinese blog).

Thus you can guess the value of `_htcookiesalt2` easily. For example, use CSRF token generated by `getSecurityToken()`, which generates token with a similar approach.

![](http://paper.seebug.org/content/images/2017/02/B80FAFEC-AF23-4839-8FEA-0FAB74B2A325.png)

[The bug in PHP has been reported](https://bugs.php.net/bug.php?id=73860). The bug is not confirmed yet but dev from PHP said it is not good practice to generate salt using `session_id`.

**Comment by phy25** [comment]
@splitbrain This seems like a public blog post published yesterday. And code samples have been released in the blog post (all the images, which contain no Chinese).

**Comment by phy25** [comment]
OK I just invesigated further. I just missed an important part in the blog.

`getSecurityToken()` => PassHash::hmac('md5', session_id().$INPUT->server->str('REMOTE_USER'), auth_cookiesalt());
`media_get_token()` => substr(PassHash::hmac('md5', $token, auth_cookiesalt()),0,6)

Now `auth_cookiesalt()` can be treated as a constant value. In most cases `$INPUT->server->str('REMOTE_USER')` equals to `""`. If you make `session_id()` equal to the fetch URL `$token`, you can get exactly the same token of `media_get_token()` by `getSecurityToken()`. Thus the token check can be bypassed.

**Comment by splitbrain** [comment]
Ohhhh.... now I get it. I saw the weird HTTP url session value in the screenshot, but I didn't make the connection.

Okay. So the actual _htcookiesalt2 is not exposed at all. This is simply using the CSRF mechanism to calculate the token for the media stuff. Clever!

Now I can think about a fix. Thanks for your help.

**Comment by niubl** [comment]
I am sorry I just go out for dinner and does't see the replay. The vulnerability is not critical becase a SSRF need to set the fetchsize not zero first. By default the fetchsize is zero.

**Comment by niubl** [comment]
@splitbrain Will you apply for CVE for this vulnerability?
