### ISSUE TITLE
AuthLDAP doesn't provide a cleanUser function

### ISSUE THREAD

**Issue by bug** [splitbrain/dokuwiki#1965]
Using pief's authsplit to setup separated authentication and authorization, I realize a while ago now that autocreate user accounts authenticated in an LDAP directory through the bundled authLDAP plugin are case sensitive. So the users.auth.php file contains several lines such as:

joe:whateverpasswordunusedwithldapbackendauth:test:joe@localhost.localdomain:user
Joe:whateverpasswordunusedwithldapbackendauth:test:joe@localhost.localdomain:user
JOE:whateverpasswordunusedwithldapbackendauth:test:joe@localhost.localdomain:user

LDAP being case insensitive this all matches the same user account. The authLDAP should provide a cleanUser() function to lowercase (and maybe some other string replacements) the username written in the users.auth.php file.

**Comment by splitbrain** [comment]
Hmm, I wonder if it's authldap's task to do this lowercasing or if authsplit should do it for all auth backends returning false in `isCaseSensitive()`?

**Comment by bug** [comment]
For LDAP RFC 4519 tells 'uid' is case-insensitive. That said cn attribute can be used for authentication and it is case sensitive.

**Comment by bug** [comment]
A side effect is that this issue can lead to a priviledge escalation. If a user is confined by ACL to a limited namespace such as:

username:thepassword:User Name:user@domain:limited

then, loging in as USERNAME results in a new line in the users.auth.php conf file with the default group rights (in my case 'user'):

USERNAME:thepassword:User Name:user@domain:user

and the default group 'user' could have more rights granted to username than the ones from the 'limited' group.

**Comment by splitbrain** [comment]
I understand that, however the authldap plugin already signals that usernames are case insensitive and ACLs are checked case insensitive accordingly. The unwanted behavior here is introduced by the splitauth plugin which stores the usernames for use beyond of what auhtldap knows about. So I am wondering if it should be fixed in authldap since it is not an issue when the plugin is used standalone...

**Comment by pief** [comment]
The problem I see is that authsplit shouldn't implement any kind of case-modifications itself by default because that could affect other combinations of auth plugins. For example, what if a certain auth plugin expects usernames to be actually uppercase, for whatever reason.

Maybe I'm on the wrong track but I can see see two solutions.

One, replace authsplit's current `cleanUser()` implementation of calling

```
        $result = $this->authplugins['primary']->cleanUser($user);
```

with

```
        $result = $this->authplugins['secondary']>-cleanUser($this->authplugins['primary']->cleanUser($user));
```

This would however assume that a.) the secondary plugin does case altering (where again one can bring the argument that the plugin when used on its own has no justification to do so) and b.) the secondary plugin's `cleanUser()` does not do anything that counters the cleaning done by the primary plugin's `cleanUser()`.

So, solution two would probably be more correct: extend authsplit's `cleanUser()` to _optionally_ apply case conversion _if_ (and only if) primary and secondary plugins' `isCaseSensitive()` do not match _and_ a suitable new config setting has been configured to either "Uppercase" or "Lowercase". If that setting would have been left at its default, "Do not change case", authsplit should log an error. 

Comments?

**Comment by pief** [comment]
@bug: Also, one thing I don't understand: in [the authsplit ticket](https://github.com/pief/authsplit/issues/8#issuecomment-282876764), you mentioned that you'd get "cloned users" even when using authldap alone? That can't be true then if authldap signals that it's case-insensitive?

**Comment by bug** [comment]
@pief No of course, with authldap alone there is no duplicated line, my comment in the authsplit ticket was confusing.

**Comment by bug** [comment]
Solution two looks fine.

**Comment by splitbrain** [comment]
Yeah I think solution two makes sense.

**Comment by pief** [comment]
Ok, then we can close it here and I'll handle it over in the [authsplit Ticket](https://github.com/pief/authsplit/issues/8) :)
