### ISSUE TITLE
User with only "upload" permissions can overwrite existing media files

### ISSUE THREAD

**Issue by karjaneth** [splitbrain/dokuwiki#2015]
On the documentation page about ACLs, In the third note at the bottom of [Background Info](https://www.dokuwiki.org/acl#background_info), it states (emphasis mine):

> Note: The delete permission affects media files only. Pages can be deleted (and restored) by everyone with at least edit permission. **Someone who has upload permissions but no delete permissions can not overwrite existing media files anymore**.

However, it appears that this is not the case. I created a user with "upload" permissions over a namespace, and was (correctly) able to upload files as that user and not delete files. But if I select an existing file, I can click "Upload new version", and go through that process to select a new file, check the "Overwrite existing files" box, and upload it, overwriting the file that was already there. Unless I'm misunderstanding something, that shouldn't be able to happen.

We just noticed this, and I don't know how long the behavior has been this way, but we did notice several issues (#1853, #1863, #1864) and a pull request #1878  relating to the Media Manager _not_ overwriting files, so maybe that broke the permissions somehow?

**Comment by splitbrain** [comment]
Seems you're right. I guess rarely anyone uses that kind of configuration. I have to look into that - patches welcome.

**Comment by splitbrain** [comment]
Turns out this is not a bug but intended behaviour. See https://github.com/splitbrain/dokuwiki/blob/master/inc/media.php#L445

The behaviour changed when revisions for media files were introduced (only the documentation apparently never got updated accordingly). Reasoning was, that when you can upload it's okay to overwrite files because they can easily be restored now (which wasn't the case before). This should bring it more in line with how editing permissions for pages work.

So it works as intended. It would be open for debate if that's good, though.

**Comment by karjaneth** [comment]
Aha! That explains it. The behavior does make sense IMO for normal cases. We ran into it because we're structuring our ACLs a certain way to best make use of the [publish plugin](https://www.dokuwiki.org/plugin:publish). It doesn't support drafts for media files, so we were trying to disallow "editing" of media files while still allowing new ones to be created. It's an odd use case and is really more a problem with the publish plugin rather than the normal ACL behavior.

Unless anyone objects, I could edit the ACL documentation to make it clear that having the upload permission allows a user to overwrite files.

**Comment by Klap-in** [comment]
"Unless anyone objects, I could edit the ACL documentation to make it clear that having the upload permission allows a user to overwrite files."
Good idea. Please include that this behaviour depends on the setting of https://www.dokuwiki.org/config:mediarevisions . The new behaviour happens if 'mediarevisions' is enabled. Otherwise the original behaviour occurs.

**Comment by karjaneth** [comment]
Documentation has been updated
