### ISSUE TITLE
Make DokuWiki see / recognize Markdown ".md" Files

### ISSUE THREAD

**Issue by a123qwertz567** [splitbrain/dokuwiki#2166]
Hello,
Normally I write all my documentation in markdown. So I use DokuWiki with the Markdown plugin, which works fine for me.
But I have to rename all my files to a `.txt` ending to make them appear on the sitemap. For now I use a workaround by symlink the `file.md` to `file.txt`.

Is there any way I can convince DokuWiki to make direct use of the `.md` extension?

**Comment by Klap-in** [comment]
Did you look if you could create a plugin for adding this?

**Comment by splitbrain** [comment]
This would require a define for the default extension somewhere. Introducing this would probably mean changing quite a few places. Even then, since nearly nobody would ever change it from the default `.txt` chances are high that we'd miss places and that plugins would not support it. This means it would most certainly break functionality in unexpected places for people using this setting, creating bug reports and support questions...

So sorry, it's not worth the trouble.

**Comment by phy25** [comment]
I agree that it's hard to implement this with keeping backward-compatibility, as plugins usually assume everything ended with ".txt". Though, it seems easy to patch it, if you are able to fix every subsequent incompatible code in your environment.

FYI, after a straightforward search with `.txt` in the codebase (without `_tests`):

- inc\pageutils.php:304,306 (generate filename)
- inc\search.php:252-490 (file discovery)
- inc\Action\Export.php:53 (export filename)

**Comment by Klap-in** [comment]
(There are more than 1000 published plugins. I tried to redo the plugin survey, to study the use of old and deprecated dokuwiki parts. My experience was that setting up a new survey is too cumbersome, so going a step further and using the survey output to warn plugins authors is even more work... Other experience is that plugin authors often use easy approaches. I guess that just using .txt will be one of them... So my guess it fixing other plugins is the most difficult part of this)
