### ISSUE TITLE
Plugin Update behind proxy fails

### ISSUE THREAD

**Issue by mamoep** [splitbrain/dokuwiki#2270]
I am testing Dokuwiki 2017-02-19e "Frusterick Manners" on CentOS 7.4 with Apache 2.4 / PHP 5.4.

The plugin update for HTTPS sources doesn't work behind our corporate proxy. I analyzed the traffic and found out the TLS handshake is done wrong. Instead of the the destination host "github.com" the proxy server DNS name is put in the SNI "Server Name" field of the request. The proxy server tries to validate the request and resets the connection.

I tried to use the HTTPClient.php from the master branch, but the issue exists there too.

I made a screenshot from Wireshark.
![dokuwiki_sni_error](https://user-images.githubusercontent.com/26142342/37036309-8bff3a8a-214f-11e8-9a67-bda9de74b837.png)

**Comment by phy25** [comment]
Hi, this is a duplicate of #2265. A workaround PR will be made later to master, but now you can patch your `inc/HTTPClient.php` file (for release_stable_2017-02-19e only), replace line 602 - 617 with (untested with PHP 5.4, but it should work fine):

```php
            $negotiated = false;
            if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')){
                $negotiated = stream_socket_enable_crypto($socket, true, STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT);
            }
            if(!$negotiated){
                // @link http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122
                $crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT;
                if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
                    $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
                    $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
                }
                $negotiated = stream_socket_enable_crypto($socket, true, $crypto_method);
            }
            if ($negotiated) {
                $requesturl = $requestinfo['path'].
                  (!empty($requestinfo['query'])?'?'.$requestinfo['query']:'');
                return true;
            }
```

Also please note that the minimum PHP version required for the next stable version release (as well as the master branch) is PHP 5.6+. You are using PHP 5.4, so the current master branch fails.

**Comment by mamoep** [comment]
I think I have a different issue here. I replaced the lines but the issue persists. Line 600 looks more promising for my issue:
```
            // set correct peer name for verification (enabled since PHP 5.6)
            stream_context_set_option($socket, 'ssl', 'peer_name', $requestinfo['host']);
```
Does that mean it won't get set for PHP 5.4? Any workaround for that?

**Comment by Klap-in** [comment]
PHP 5.4 is end of life since half of 2015. Further, it is not supported by DokuWiki anymore.
I would recommend to update to a supported version.

**Comment by mamoep** [comment]
PHP 5.4 is still the default in RHEL 7, and RedHat is still back porting fixes. Anyway I tested with PHP 5.6 and it works. Thanks for the fast response!

**Comment by phy25** [comment]
For future travelers to here, because I posted some complex (and broken) code above and after some testing:

- If you are using master and PHP 5.6+: No issue on this
- If you are using stable (~release_stable_2017-02-19e):
  - As #2265 mentioned, just replace `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_SSLv23_CLIENT` [in inc/HTTPClient.php#L606](https://github.com/splitbrain/dokuwiki/blob/release_stable_2017-02-19e/inc/HTTPClient.php#L606)
  - PHP 5.6+: You can also cherry-pick commit f7813a6826e073e65a6fe7b667c199aa1e660e47 in master (next stable release) or use master branch at your own risk.
  - PHP 5.3, 5.4, 5,5: The one-line fix works, but you should really consider upgrading your PHP version, because "PHP 5.4 is end of life since half of 2015. Further, it is not supported by DokuWiki anymore" (due to some language syntax breaking changes).

**Comment by KaiMartin** [comment]
Just a heads up from a site which runs dokuwiki behind a proxy with php 7.2:
The one line patch in inc/HTTPClient.php mentioned above was sufficient to fix the problem. This allowed me to update to the recently released dokuwiki version 'greebo' via the upgrade plugin. No cherry picking needed. The upgrade did overwrite HTTPClient.php. But since the problematic setting  has been officially patched everything is officially fine now.

---<)kaimartin(>---
PS: Thank you for maintaining this most useful piece of software!
