### ISSUE TITLE
file name problems with Korean on Windows

### ISSUE THREAD

**Issue by sosungkuk2** [splitbrain/dokuwiki#2282]
It is a sentence using Google translation.
Please understand the sentences as well.

Currently, I first installed Dokuwiki with the "Detritus" version and used only the upgrade files on the latest announced version of "Frusterick Manners".

However, when creating a document, if the name of the document is Hangul and the word "테(Te)" is entered, the file name of the document is not generated from that character, and a phenomenon of being cut is found. {Interestingly, the "태(Te)" is generated without problems.}

My server's language is not changing the language setting while using Windows Vista and documents are created in a format like %ED other than UTF-8.

I have searched for a Korean site, but I have not found an answer to this phenomenon, so I have found it on the Dokuwiki site, but I will come here and write a sentence, what should I do?

**Comment by splitbrain** [comment]
It's unclear what exactly the problem is you're describing.

for starters I created two pages that both seem to work as expected:

* https://www.dokuwiki.org/playground:%ED%83%9C_te
* https://www.dokuwiki.org/playground:%ED%85%8C_te

Please answer the followoing questions:

* What's your setting for the `fnencode` option?
* What version of PHP are you running?
* What exactly is the name of the page you created?
* What exactly is the name of the file name that resulted on creating that page?
* What did you expect to happen?

**Comment by phy25** [comment]
I am closing this because of lack of response, but feel free to add more information and I can reopen the issue if necessary.
