### ISSUE TITLE
Plugin List is unsorted on Configpage ( noticed since Frusterick Manners)

### ISSUE THREAD

**Issue by fstorck** [splitbrain/dokuwiki#2341]
I've noticed, that my plugin list in the config page is completely unordered. 

It happens on this setup:
os	Linux
webserver	Apache
php_version	5.6.33-0+deb8u1

It doesn't happen on this setup:
os	FreeBSD
webserver	Apache/2.4.29
php_version	5.6.33

I've noticed it since Frusterick Manners, but it also happens on Greebo. It's not critical but annoying on longer plugin lists.

![grafik](https://user-images.githubusercontent.com/501666/39173570-61231954-47a5-11e8-8097-387d296199a3.png)

**Comment by Klap-in** [comment]
Could be that it is ordered 'naturally'. i.e. it is shown in the order that is written once to disk.

Which sorting would you propose for the best user experience?

**Comment by fstorck** [comment]
Well, alphabetical would be most natural I think. You have usually the name in mind, so that would be handy enough I think. Especially in bigger lists.

**Comment by ssahara** [comment]
The Extension Manager shows installed plugins in alphabetical order, therefore it would be convenient for most admins to show same order in the config manager.
https://github.com/splitbrain/dokuwiki/blob/1121b972bffbf7afb0aef5dfb54f8857c73c3c56/lib/plugins/extension/helper/gui.php#L44

**Comment by ElScotto** [comment]
This patch fixed the problem for me:

`--- lib/plugins/config/settings/config.class.php.original	2017-08-24 04:21:36.000000000 +1000`
`+++ lib/plugins/config/settings/config.class.php	2019-09-19 11:23:24.669117294 +1000`
`@@ -352,6 +352,7 @@`
`                 // remove this plugin from the list`
`                 $idx = array_search('config',$list);`
`                 unset($list[$idx]);`
`+                sort($list);`
` `
`                 trigger_event('PLUGIN_CONFIG_PLUGINLIST',$list);`
`                 $this->_plugin_list = $list;`

**Comment by phy25** [comment]
@ElScotto Feel free to submit a PR if you want :-)

**Comment by fstorck** [comment]
Yes, please do so!

**Comment by ElScotto** [comment]
> 
> 
> @ElScotto Feel free to submit a PR if you want :-)

Unfortunately, I'm an RCS/SCCS dinosaur and do not understand git yet, so my apologies for my inability to submit a pull request.

I know how to clone a repo, create/checkout a branch in that clone and add/commit a changed file to the branch I've made.
However I'm buggered if I can understand how a "pull request" works to check my change back in, and the Github guide does not make it any clearer.

So, rather than stuff around any further, I've attached the patched file here (as modified from a copy from the "master" branch).  It's got an extra ".txt" extension so that Github would upload it.

Hopefully someone here will be able to work it back into an "issue2341" branch in Github so that it can be merged into the "master" branch.
[config.class.php.txt](https://github.com/splitbrain/dokuwiki/files/3630669/config.class.php.txt)

**Comment by ElScotto** [comment]
@phy25 @fstorck 
I have a feeling that I need to be invited or otherwise granted write access to the DokuWiki repository because I cannot create a pull request within the github web site, nor can I submit the "issue2341" branch pull request that I made on my Linux systems using the "git" commands line back to the repository.

**Comment by LarsGit223** [comment]
You need to first fork DokuWiki to your account. Then clone from that repository (e.g. ElScotto/DokuWiki). You can then push back to that repository and create a PR from there.

**Comment by ElScotto** [comment]
> 
> 
> You need to first fork DokuWiki to your account. Then clone from that repository (e.g. ElScotto/DokuWiki). You can then push back to that repository and create a PR from there (from ElScotto/DokuWiki to splibrain/DokuWiki).

Thanks Lars!
(As I said in a previous message, I'm still getting the hang of "git")
