### ISSUE TITLE
Small visual bug: Page Tool remains selected

### ISSUE THREAD

**Issue by jobhh** [splitbrain/dokuwiki#2366]
Clicking and dragging a button in the page tools will result in that button remaining selected:

![image](https://user-images.githubusercontent.com/2331451/39513395-77c47a2c-4df4-11e8-8bcf-9437765c33c9.png)

When hovering over the page tools again it also looks odd:
![image](https://user-images.githubusercontent.com/2331451/39513471-c19efe4c-4df4-11e8-89b8-adf7182374ca.png)

Clicking elsewhere (inside or outside of the browser) will de-select it. Chrome/Firefox/Edge have the same beheaviour.

----------------------------

I encountered this because the "Rename Page" or "Export to PDF" buttons don't change URL like the other tools. It happens in both Greebo and Frusterick Manners.

Greebo:
![image](https://user-images.githubusercontent.com/2331451/39513144-a1b833a6-4df3-11e8-9051-508e3b338ee8.png)

Frusterick Manners:
![image](https://user-images.githubusercontent.com/2331451/39513251-0e2627dc-4df4-11e8-9d1b-7355438b2120.png)

**Comment by Klap-in** [comment]
If I remember correctly from some testing in the past, it looks like the focus is set, but not removed. (the applied styling is for the case the button is focused)

**Comment by phy25** [comment]
Thanks for raising the issue. I agree with @Klap-in, and:

1. Showing user focus is important and we cannot just remove that effect for focus;
2. Let's regard this page tool box as a menu, and in terms of dragging:
   - Remaining the focus after dragging seems a standard practice: not only browser's "native" implementation making it happen in this case (some quick example: Gmail, Windows Explorer...). And personally I think it right for accessibility;
   - Dragging should be supported with page tool icons (e.g. I can drag the link to the tab bar)
   - After dragging, the menu should remain open, but currently the menu only checks for `:hover` rather than `:focus`, making the one item stand out. The new [`:focus-within` selector](https://developer.mozilla.org/docs/Web/CSS/:focus-within) is very efficient in fixing this.
3. In terms of clicking, the menu should disappear after that, so we can make use of JavaScript to blur focus (and just tested, seems like no accessibility issue).
4. Focus and hover state can be on two different elements, and because DokuWiki's default styling is simple, they don't distinguish. People seems more tolerant about this styling (I have seen a lot of these happening). But if anyone cares, maybe we can change the focus state to something lighter?

Wow, several good first issues :-)

**Comment by phy25** [comment]
Closing because #2534 has been merged, but feel free to reopen if you have other observations.
