### ISSUE TITLE
JS broken in Greebo using IE 9

### ISSUE THREAD

**Issue by medmen** [splitbrain/dokuwiki#2408]
After upgrading from frusterik to greebo, all javascript-based functionality in dokuwiki is gone when using Internet Explorer 9 (i.e. editor buttons missing, checkboxes in plugin page missing).

IE 11, Firefox and Opera work fine.  Disabling all plugins does not solve the problem.

IE 9 shows javascript error somewehre in Jquery Migrate code (can only reproduce at work, but have no github access there, so sorry about missing exact error description).

**Comment by splitbrain** [comment]
I don't think it's worth to even look at IE9 bugs anymore. If you have a sensible patch, feel free to open a PR, but I won't spend any more time on a dead horse.

**Comment by selfthinker** [comment]
I think it's important to note/update which version of IE DokuWiki supports. 

https://www.dokuwiki.org/browser (linked from requirements) says:
> DokuWiki developers take care to make DokuWiki usable in Internet Explorer 8 or higher.

I just updated that to say "IE9" because Frusterick Manners dropped IE8 support.
Do we know if that should be updated to an even higher number? I couldn't find anything in the [changelog](https://www.dokuwiki.org/changes) which suggests that.

What's also really important to point out is that DokuWiki mostly supports progressive enhancement. That means that even when JavaScript is not working, all main functionalities of the wiki engine will still work, but are just a bit cruder.

**Comment by medmen** [comment]
Thanks @bwanders this fixes the ie9 issue indeed, so i will close this issue
