### ISSUE TITLE
Please remove unintended google search

### ISSUE THREAD

**Issue by chang-zhao** [splitbrain/dokuwiki#2588]
When /inc/parser/renderer.php meets a link with an "unknown" protocol, such as "file://", clicking that link sends the contents of the link to Google search WHICH WAS OBVIOUSLY NOT INTENDED BY THE USERS and can disclose personal information.

```
  821      function _resolveInterWiki(&$shortcut, $reference, &$exists = null) {
  822          //get interwiki URL
  823          if(isset($this->interwiki[$shortcut])) {
  824              $url = $this->interwiki[$shortcut];
  825          } else {
  826              // Default to Google I'm feeling lucky
  827              $url      = 'https://www.google.com/search?q={URL}&amp;btnI=lucky';
  828              $shortcut = 'go';
  829          }
```

Please remove this feature.

**Comment by phy25** [comment]
Good observation. Some clarification: 

> When /inc/parser/renderer.php meets a link with an "unknown" protocol, such as `file://`...

The link in this situation (`file://...`) just doesn't render at all, instead of guiding user to Google. [The code mentioned](https://github.com/splitbrain/dokuwiki/blob/30def7da1b644298a9135d5b6e6a9cc9838e951b/inc/parser/renderer.php#L826-L828) (whose idea exists for 10+ years) handles interwiki syntax like `file>...`.

Demo: https://www.dokuwiki.org/playground:issue2588

I wonder where is better for us to direct users to in this situation? Maybe the first item in `interwiki.conf` (as the default/fallback)?

**Comment by FosseWay** [comment]
While I'm not convinced that the fallback Google I'm Feeling Lucky behaviour is presents much of a risk for most users, I don't see that it has much value either.

As for how to handle undefined interwiki types, my suggestion is to create no link at all, and add a warning message.

**Comment by selfthinker** [comment]
I'd rather make it configurable, for example via a `default` keyword in the interwiki config file.

**Comment by phy25** [comment]
Not sure if it's worth adding a new syntax of interwiki link ignoring the wikiname `>query` (equals to `default>query`).
