### ISSUE TITLE
paste as markup

### ISSUE THREAD

**Issue by glensc** [splitbrain/dokuwiki#2657]
gitlab has super awesome feature, that if you copy existing markdown as html, it is able to format that back as markdown.

dokuwiki should do the same.

also, dokuwiki could understand `[[wp>Title]]` links and convert those links to markdown as well.

**Comment by Klap-in** [comment]
This conversion is quite complicated (to perform really complete).

A very recent (still experimental) plugin that could has this feature is: https://www.dokuwiki.org/plugin:prosemirror

**Comment by Klap-in** [comment]
A little testing shows that copy-pasted html from a wiki article will be recognized by the prosemirror plugin. However it seems to be limited at the moment. Syntax like bold and heading works, urls not.
(If I try pasting text with urls at https://prosemirror.net/examples/basic/ it is working..., so it should be possible in future, I guess.)

Because this needs a really advanced inverse renderer, exactly what e.g. prosemirror plugin and similar are solving I think is not feasible to add this to DokuWiki directly.

Maybe the CKGEdit Plugin supports pasting original html as well, but I could not test it: https://www.dokuwiki.org/plugin:ckgedit
