### ISSUE TITLE
Dokuwiki creates empty sessions for anonymous users

### ISSUE THREAD

**Issue by fgm** [splitbrain/dokuwiki#2662]
This causes extra load on the servers, which would best be avoided. 

Some visits actually add data to the anonymous session created, but most just create an empty session, which by default will be written to disk (e.g. /var/lib/php5/sessions/* on Debian), only to be removed at the next cleaning pass, causing extra disk activity which could be avoided by late-starting sessions, only initializing them when there is some actual data to save to the session.

**Comment by splitbrain** [comment]
Every page visit should write session data, because it is used for the breadcrumbs feature. Late starting sessions may require some significant change to DokuWiki's session handling - something I don't feel is worth it (unless you want to take this project on). I'm closing this, but feel free to come back with a pull request.

**Comment by fgm** [comment]
I'm afraid I don't have enough time for it, but I'll keep it in mind, thanks for answering.
