### ISSUE TITLE
TOC "pushes" content down

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki#2751]
Hi,

_Re title: sorry, I don't know how to describe the problem better.  Please feel free to change the title if required._

**Issue:**

The table of content "pushes" content down when it is "too near" the TOC. See this screenshot:

![dokuwiki_toc_pushdown_1](https://user-images.githubusercontent.com/279232/56147912-7fd09a80-5fa9-11e9-967f-15d7df0ac6a6.png)

which results from the following DW page:

```
====== TOC Test ======

<WRAP group>
<WRAP third column>
text

text

text
</WRAP>

<WRAP third column>
text

text

text
</WRAP>

<WRAP third column>
text

text

text
</WRAP>
</WRAP>

===== Title 1 =====

==== Title 2 ====

==== Title 3 ====
====  Title 4 ====
```

Similar effects can be observed when e.g using the `note` plugin:

![dockuwiki_toc_pushdown_2](https://user-images.githubusercontent.com/279232/56148225-1bfaa180-5faa-11e9-8b83-b77cc53ce73a.png)

Can this be changed in a way, that the TOC floats over the effective content instead of pushing it away?

f.

**Comment by phy25** [comment]
You may want to submit issues in respective plugins' repos, because this is *really* a matter of how the plugins implement their styles.

They have to assume the width of the content be full width (without TOC), in order to style the boxes properly. It will be very difficult (as far as I know) to use pure CSS to achieve what you want with a "dynamic" width alongside TOC (on the top it's narrow, and at the bottom it's wide); JavaScript may be required to achieve a perfect style.

Again, there is hardly nothing to do with the template in core.

https://github.com/selfthinker/dokuwiki_plugin_wrap
https://github.com/LarsGit223/dokuwiki_note
