### ISSUE TITLE
dokuwiki load very very slow, cause of it must call on https://www.google.com/jsapi

### ISSUE THREAD

**Issue by ichris007** [splitbrain/dokuwiki#2783]
I’m in China and can not visit the google.com，so when I open my dokuwiki, it loads very very slowly, cause of it must call on https://www.google.com/jsapi, how can I fix this?

**Comment by phy25** [comment]
What templates and plugins are you using? By default it shouldn't call Google's jsapi.

**Comment by ichris007** [comment]
> What templates and plugins are you using? By default it shouldn't call Google's jsapi.

1. using the default template
2. plugins list below:
-BackupTool for DokuWiki
-Cache and Revisions Eraser
-Ckgedit
-Remove irrelevant entries from the change history
-Configuration Manager 
-Copy Page Plugin
-Structured Data Plugin
-edittable plugin
-Extension Manager
-hidden Plugin
-imgpaste plugin
-Indexmenu Plugin
-Info Plugin
-magnifier
-Menu Plugin
-Move plugin
-Namespace Listing 
-Numbered Headings
-OrgChart Plugin 
-Pagelist Plugin
-Revert Manager
-safefnrecode plugin
-saveandedit plugin
-Searchindex Manager
-sqlite plugin
-styling plugin
-Tab include plugin
-Tag Plugin
-Tagging Plugin
-DokuWiki Upgrade Plugin 
-Video Sharing Site Plugin
-Wrap Plugin

**Comment by phy25** [comment]
I only helped you check some of the plugins, and it looks like this is brought by `orgchart`:

https://github.com/selfthinker/dokuwiki_plugin_orgchart/blob/c452d8f3c4ec6b43c89c9f83c534ac7446f5a584/action.php#L27-L45

You may want to check the remaining plugins by disabling them one by one, to make sure nobody else is looking for Google.

- Pagelist Plugin
- Revert Manager
- safefnrecode plugin
- saveandedit plugin
- Searchindex Manager
- sqlite plugin
- Tab include plugin
- Tag Plugin
- Tagging Plugin
- Video Sharing Site Plugin
- Wrap Plugin

Closing because this is not a DokuWiki issue; please use the respective plugin repo to raise issues.

**Comment by ichris007** [comment]
> I only helped you check some of the plugins, and it looks like this is brought by `orgchart`:
> 
> https://github.com/selfthinker/dokuwiki_plugin_orgchart/blob/c452d8f3c4ec6b43c89c9f83c534ac7446f5a584/action.php#L27-L45
> 
> You may want to check the remaining plugins by disabling them one by one, to make sure nobody else is looking for Google.
> 
> * Pagelist Plugin
> * Revert Manager
> * safefnrecode plugin
> * saveandedit plugin
> * Searchindex Manager
> * sqlite plugin
> * Tab include plugin
> * Tag Plugin
> * Tagging Plugin
> * Video Sharing Site Plugin
> * Wrap Plugin
> 
> Closing because this is not a DokuWiki issue; please use the respective plugin repo to raise issues.

Thanks for your help.
