### ISSUE TITLE
feature request: two factor authentication support for fido U2F / fido2 / webauthn

### ISSUE THREAD

**Issue by appliedprivacy** [splitbrain/dokuwiki#2825]
It would be great to have strong two factor authentication via hardware tokens supporting one of the fido standards like yubikey or nitrokey.

It would be nice if 2fa could be enforced by admins and more than one token per account (backup token) were supported.

https://fidoalliance.org/specifications/

There are PHP libraries available for webauthn.
https://github.com/search?l=PHP&q=fido&type=Repositories

**Comment by phy25** [comment]
Though this is a great idea, I will close this since there is already [plugin:twofactor](https://www.dokuwiki.org/plugin:twofactor) with a variety of (sub) plugins including [plugin:twofactorgoogleauth](https://www.dokuwiki.org/plugin:twofactorgoogleauth). You may want to create the issue in [wilminator/dokuwiki-plugin-twofactor](https://github.com/wilminator/dokuwiki-plugin-twofactor/issues) instead.

**Comment by appliedprivacy** [comment]
Just for the record:
We are aware about this plugin but that implements OTP, which is based on shared secrets and significantly weaker than hardware security tokens using public key cryptography where only the public key part is needed on the server side.

It would also be great if strong authentication would be a core part of dokuwiki and not a 3rd party plugin.

**Comment by phy25** [comment]
You can still implement an auth plugin with no username required.

**Comment by Trapulo** [comment]
I'd like to use Webauthn instead of login+password (also with a second factor), but I cannot find a working solution.. :(
