### ISSUE TITLE
authplain: Deleting the last authplain user makes logins impossible on animals in a wiki farm

### ISSUE THREAD

**Issue by psy-q** [splitbrain/dokuwiki#2845]
We're using DokuWiki in a wikifarm setup and so we provide a global `conf/users.auth.php` which looks like this:

```php
# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Format:
#
# user:MD5password:Real Name:email:groups,comma,seperated
```

Then we use authchained:

```
  $conf['useacl']         = 1;
  $conf['authtype']       = 'authchained';
  $conf['plugin']['authchained']['authtypes'] = 'authad:authplain';
  $conf['plugin']['authchained']['usermanager_authtype'] = 'authplain';
```

So users are allowed to create new users through the user manager. Logging in using an AD username and then creating new users works fine. However, when the *last* authplain user is deleted in an animal, DokuWiki seems to delete that animal's `users.auth.php` file, resulting in the following error:

![image showing the errors: Problem constructing usermanager authtype: authplain; User authentication is temporarily unavailable. If this situation persists, please inform your Wiki Admin.; No ACL setup yet! Denying access to everyone.](https://user-images.githubusercontent.com/87557/63510896-0fe69980-c4e0-11e9-8192-36a2715d0f1e.png)

Creating a new `users.auth.php` file or copying the site-wide (empty) `users.auth.php` from above to the animal's conf dir fixes the problem. However, shouldn't the animal fall back to the global `users.auth.php` file by default anyway, so this issue should never appear?

**Comment by phy25** [comment]
So you have two concerns here:

1. `authplain` deleting the whole `users.auth.php` file. I believe you are deleting the user through usermanager but it should not make much difference.

The actual function executing this is `io_replaceInFile`. Usually people will set up wiki with install.php first, which will copy the content of `users.auth.php.dist` (with those comment on the top) and create the new `users.auth.php`. However you are using `authchained` which does not necessarily go through this process. Unfortunately if you add users in usermanager authplain's behavior will be only appending new user's line in the file without checking if the file exists or not.

I am not sure if checking users.auth.php is needed for `createUser()`. Maybe yes? I doubt that in your farm case, `users.auth.php.dist` does not exist in the animal folder at all, so nothing can be copied from `DOKU_CONF.'users.auth.php.dist'` and the problem will still be there.

2. fallback of missing animal config: Most of the config files used the farmer one as the default and the animal one as the local. The two acl-related one does not have a "local". The current behavior for `users.auth.php` is as follows:

https://github.com/splitbrain/dokuwiki/blob/67d5efaa1083c6734ddb4ac18f9e9ff8ffaafe93/inc/farm.php#L127-L132

I believe it was being set up like this for a reason. Maybe it's not appropriate to inherit the farmer acl options since it's more content-related? You should be able to override this behavior in your `preload.php`.

---

Honestly I don't know if changing anything in the code will improve the situation due to how farm works (it's only rewriting some DokuWiki path; I don't think the main code has any specific adaption to the farm behavior). Maybe we can improve the docs somehow?

For 1) maybe docs in plugin:authplain works though it does not seem to be that obvious; for 2) farms should be good place.

My two cents after learning how farm works today; feel free to add more inputs here.

**Comment by phy25** [comment]
For 1) I think it may be possible to redo the setup logic to get rid of the predefined file (I did remember those autogenerated config) ? However still need to take a look at the code.

**Comment by psy-q** [comment]
You're correct, `users.auth.php.dist` does not exist in the animal dir. It exists in the farmer dir, though. If I copy the one from the farmer dir to the animal dir, this makes no difference to this issue. Deleting the last user will delete the entire `users.auth.php` file.

The problem is that if we allow our wiki owners to manage users, there will inevitably be a situation where they delete the last user and trigger those prominent error messages (it has happened once already). And then it requires manual intervention from us admins.

I also found in `config_cascade.php`:

```php
        'plainauth.users' => array(
            'default'   => DOKU_CONF . 'users.auth.php',
            'protected' => '' // not used by default
        ),
```

So I wonder: If it's "not used by default", are there cases where it could be used, and is this such a case?

**Comment by phy25** [comment]
Sorry I did not mention one point: The reason that `io_replaceInFile` is removing `users.auth.php`, is because your `users.auth.php` do not have any other content. To prevent that, put some comments in the beginning, as is demonstrated in `users.auth.php.dist`:

```
# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Format:
#
# login:passwordhash:Real Name:email:groups,comma,separated
```

`protected` is config that cannot be changed using web interface. I am not sure what "not used by default" means there indeed.

So as I mentioned, I don't know if changing anything in the code will improve the situation due to how farm works (it's only rewriting some DokuWiki path; I don't think the main code has any specific adaption to the farm behavior). Maybe we can improve the docs somehow?

**Comment by psy-q** [comment]
Oh, I see! I will try the trick with the comments tomorrow. I don't know why none of our `users.auth.php` have comments. I thought they were copied from `users.auth.php.dist` on animal creation, but it seems that's not the case.

**Comment by phy25** [comment]
> they were copied from users.auth.php.dist on animal creation

I have no experience setting up a farm, but from docs it's more of a DIY process. As I mentioned before, if you use `install.php` to set up an animal, `users.auth.php.dist` does not exist in the animal folder at all, so nothing can be copied from `DOKU_CONF.'users.auth.php.dist'` during installation.

**Comment by phy25** [comment]
@psy-q About your `plainauth.users.protected` "not used by default" question, I found this, which I don't think has anything to do with the behavior you mentioned indeed (42cbd322ad0cf816cca498eeb93bb1b8e4e7db5e):

> This adds the possibility to define file with protected users in the
config cascade to be used with the plain auth mechanism.
>
> This makes it possible for farms to have way to inherit Farmer users in
animals.

I also submitted a new PR #2857, which make how install.php creates `users.auth.php` consistent with other config files (it is the only one now that copies existing template file, which does not necessarily exist in animal config folder).

For the config file in use, you do need to **add comments at the beginning of the file manually as soon as possible for a security concern**.

**Comment by psy-q** [comment]
I've added the comments and tested, you're right, the problem does not appear as soon as any comments are in the file.

I've adapted our animal creation script to write comments to these files if they don't exist yet instead of leaving things to chance :)

Thanks a lot for your help with this and for the PR to bring the behavior in line with the other config files!
