### ISSUE TITLE
feature: Interlanguage

### ISSUE THREAD

**Issue by icf20** [splitbrain/dokuwiki#2862]
any plans to have proper interlanguage setup like mediawiki?

**Comment by phy25** [comment]
Could you please explain what specific feature you are looking for?

See also https://www.dokuwiki.org/localization

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/65181149-b5991400-da5e-11e9-82c4-7ce0b4a19f53.png)

this

**Comment by splitbrain** [comment]
@icf20 please take more than 5 seconds to describe what you want and what you have tried.

**Comment by icf20** [comment]
oh is not obvious? 

here https://www.mediawiki.org/wiki/Interlanguage_links is how media wiki does it

**Comment by phy25** [comment]
Please see https://www.dokuwiki.org/localization

**Comment by Klap-in** [comment]
A language choicer is available via https://www.dokuwiki.org/plugin:translation

**Comment by icf20** [comment]
> A language choicer is available via https://www.dokuwiki.org/plugin:translation

that should work but is a plugin and the update for said plugin can be dropped anytime for any reason :face_with_head_bandage:

**Comment by phy25** [comment]
@icf20 I still think a plugin is OK because this feature does not seem to require any hooks beyond plugin API, and I personally prefer to keep DokuWiki simple by using plugins (and I don't think we have this much resource to maintain it in core).

If you feel that there are better reasons or if you are willing to provide the necessary resources e.g. maintaining this feature with enough unittests, please let us know.

**Comment by Michaelsy** [comment]
In essence, the Wikipedia language links feature is realized via interwiki links, which also exist in DokuWiki: https://www.dokuwiki.org/interwiki

@icf20 If you want to have it exactly the same as in Wikipedia, then there would still be the issue of getting this page-related links into the sidebar. That means there is no problem to put the language links into the normal content of a wiki page.
