### ISSUE TITLE
bootstrap-theme

### ISSUE THREAD

**Issue by j0te** [splitbrain/dokuwiki#3121]
Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6

**Comment by j0te** [comment]
bootstrap3-typeahead.min.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1
    at bootstrap3-typeahead.min.js:1

**Comment by j0te** [comment]
wiki was broken.... had to change dokuwiki/conf/local.php

**Comment by Klap-in** [comment]
You can temporary disable the feature flag js_defer in the config manager.

https://www.dokuwiki.org/config:defer_js (not yet existing)
https://github.com/splitbrain/dokuwiki/pull/2974

**Comment by j0te** [comment]
> You can temporary disable the feature flag ‘defer_js’ in the config manager.
> 
> https://www.dokuwiki.org/config:defer_js (not yet existing)
> Introduced in: #2974

/conf/local.php
$conf[defer_js] = true

???

**Comment by Klap-in** [comment]
Please set it to `false` to disable it.

**Comment by j0te** [comment]
> Please set it to `false` to disable it.

$conf[defer_js] = false;  # /conf/local.php is not working....

**Comment by phy25** [comment]
To reformat the code, you want to put the following line in `/conf/local.php`:

```php
$conf["defer_js"] = true;
```

@j0te Does that work for you?

**Comment by nipuli** [comment]
Hi,
I went into the issue, admin-menue not callable at all after upgrading to Hogfather.
So I tried Klap-in's solution, and it worked for me. Thanks!

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.
