### ISSUE TITLE
Hogfather: sidebar disappears

### ISSUE THREAD

**Issue by rellampec** [splitbrain/dokuwiki#3123]
Not quite sure if it relates to the [minimap](https://www.dokuwiki.org/plugin:minimap) plugin I am using in there. The below is the only content of the sidebar:

```
~~NOCACHE~~
<minimap>
```

After the upgrade using the [upgrade](https://www.dokuwiki.org/plugin:upgrade) plugin, it seemed to work fine for some minutes (perhaps it was still cached?)... then a page refreshed made the sidebar disappear. I am using the **default theme/template** of dokuwiki.

I reverted the upgrade by restoring the backup. I did not check if there were other plug-ins that are not working after the upgrade. However, it would have been really wise to notify all the plug-in authors if they need to upgrade their plug-ins and some guidelines of most common changes to the code. 

It's not a complain, just a suggestion for the next time... as i suspect many have reverted the upgrade and really few will keep it with the latest version until the plug-in issues are fixed.

**Comment by phy25** [comment]
Thank you for your feedback. I noticed that the plugin you mentioned is updated today. What is the version of the plugin that you are using? Could you manually upgrade the plugin to see if it works?

A sad fact is that our automatic tests are not covering every corner case, and plugins may have unexpected usage to the API and are usually not tested against master until someone actually upgrades, so that happens.

**Comment by rellampec** [comment]
I guess I need to have a `testing` environment... now I reverted the upgrade. Perhaps it has something to do with the issue pointed out in this thread: https://github.com/splitbrain/dokuwiki/issues/3129

**Comment by phy25** [comment]
What other plugins do you have? Could you disable other plugins to see if that is still happening?

**Comment by rellampec** [comment]
(working fine now)
