### ISSUE TITLE
Hogfather - plugins with problems of syntax

### ISSUE THREAD

**Issue by ccastello** [splitbrain/dokuwiki#3127]
I have upgraded with _DokuWiki Upgrade Plugin_
Extensions are blocked the use of dokuwiki (Fatal error) :

- _French Typography_
- _FAQ plugin_
- _ToDo_

The problem was the same : syntax of functions _render_ and _handle_

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.
