### ISSUE TITLE
Upgrade to Hogfather leads to html 500 error

### ISSUE THREAD

**Issue by gw72** [splitbrain/dokuwiki#3128]
Following an upgrade to hogfather, the wiki no longer loads at all, giving an html 500 error. 
After restoring to the previous version, I have found that this problem occurs only when any of the following plugins are enabled:

Include
Publish
Refnotes
Showlogin

**Comment by meierdan** [comment]
same for me, got error 500

**Comment by Klap-in** [comment]
Please check the error log of your webserver, and share the errors.
If the errors are in the plugins, please report for each of them which error occurs, such that the author can have a look. 

There have been significant refactoring of the source code of DokuWiki, these has unfortunately effects on the existing plugins. So hopefully we can find and solve quickly which plugins were affected.

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.

**Comment by gw72** [comment]
Hi. I realise that the issues are related to extensions but given that so many extensions seem to be affected and the consequence of upgrading is complete failure of the wiki to load, I thought it was worth raising here.
One error I receive that does no specifically seem to relate to a plugin is:
 [error] [client 193.x.x.x:0] File does not exist:....../public_html/wiki-test/lib/exe/indexer.php

**Comment by splitbrain** [comment]
@gw72 please open new issues for new (unrelated) problems. `lib/exe/indexer.php` no longer exists. It's functionality has moved to `lib/exe/taskrunner.php`
