### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by id027102** [splitbrain/dokuwiki#3159]
After last upgrade (rc3...) also with rc2 (first upgraded yesterday)
Error with apache2  ......require_once(....../inc/JSON.php) failed to open stream .........
in ...../lib/plugins/indexmenu/action.php on line 160
Solved with comment out or delete line 160 in action.php (# require_once DOKU_INC.'inc/JSON.php';)
../inc/JSON.php is listed in deleted files and so the error

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's (indexmenu) code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.

**Comment by id027102** [comment]
You cannot forward , for me the problem is solved by removing the line

Closed
