### ISSUE TITLE
Strange behavior between project leader and plugin devs since switch to RC being the "recommended" download and already running installations updating to

### ISSUE THREAD

**Issue by joerg-nafcom** [splitbrain/dokuwiki#3201]
I sent this feedback via email already but got no reply, so I am writing something about this here on Github hope somebody would care to feedback and maybe do corrections and improvements accordingly.

I have noticed several Strange behavior between project leader and plugin devs since switch to RC being the "recommended" download and already running installations updating to.

I decided to use Dokuwiki in 2016 because of the ease of use, so my 20 international team members wouldn't have to relearn things they know from World (WYSIWYG plugins)

I never had to worry much, the update plugin would update the system and developers of plugins would carry along.

Now suddenly, the decision to use an RC as "recommended" and totally changing the way Dokuwiki works on some places, made many plugins unusable and these reactions when reporting it from Devs:

Either:
No feedback,
Or: 
"We will look into it once the final of the RC is out" which can take months and years and until then it remains broken (and unusable in many cases".
And in the forum threads were there were discussions about it, those threads have been locked so nobody except the project owner. 
And several plugin coders announced their frustrations about this as well announcing to leave the project.
There was a reply like "Don't give up we will work it out" to that locked thread in particular, but is no use if it is still locked and nobody can reply to it anymore.

Right now it feel like Dokuwiki is shooting itself in its foot. This way it does lose plugin devs and users.

I don't know what lead to the decisions to make RCs the "new recommanded" way to go and I do not know what changed in the system that plugin coders ignore the RC and deny either fixing their plugin or even leaving the project altogether, but I seriously hope something is done about it.

At the moment it looks like "close eyes and ignore" is the way this thing ithing is handled and it frightens me,.

I am having a real usecase here with 20 people using our Wiki and now I am unsure what will happen to Dokuwiki or if this is a dead end.

**Comment by splitbrain** [comment]
This is not really the right place to discuss. The forum would be better suited for this. But I'll try to answer your concerns anyway.

* The upgrade plugin is not a bundled plugin. The official way to upgrade is manually.
* The plugin installs the `stable` branch. We always used the `stable` branch for RCs as well. However we stopped doing RCs for a long time (read https://www.patreon.com/posts/why-we-dont-do-8173276) I guess it's a bit unfortunate how this is translated to the plugin's description (feel free to adjust it on the wiki page)
* it is always your decision if and when you do an upgrade
* We did RCs this time *because* we changed so much and anticipated problems
* compatibility with hogfather has been restored for many plugins already (either by changes we did in RC3 or by updates done by the authors)
* plugin authors abandon their plugins all the time. you just don't notice until an incompatibility arises. we cannot do anything about this. I totally understand when someone wrote a plugin 5 years ago and aren't using it anymore that they have zero interest in fixing it for the new release. That's a sad reality of OpenSource
* it would be helpful if you could link to the threads you feel where locked for the wrong reasons. if you refer to https://forum.dokuwiki.org/d/17852-new-update-has-broken-everything/ that thread has been closed because the topic was too broad (on-topic posts per plugin are more helpful) and the issues within have been solved. I gave Myron direct pointers in how to fix his plugin in a issue in his repository and he has a new version ready that is Hogfather compatible already - so I *did* work with him to resolve the issues
* I wrote a whole post on what plugin authors can look at to fix their plugins here https://www.patreon.com/posts/hogfather-plugin-38090834

I will close this issue, but I do encourage you to create a forum post if you think there's more to discuss. And please feel free to link to specific cases in your post - I'm happy to have a look at it and give some feedback.
