### ISSUE TITLE
After update to “Hogfather” I can’t reach admin page

### ISSUE THREAD

**Issue by F3000** [splitbrain/dokuwiki#3218]
I have updated from Greebo .

I can use all feature but when I click on "Admin" I see an empty page .

Any idea ?

**Comment by splitbrain** [comment]
please read https://www.dokuwiki.org/changes#release_2020-07-29_hogfather

**Comment by F3000** [comment]
Hi Andreas,

thanks . But can't find the any hint in the upgrade Infos .

I have updated all plugins first .

What did you think ?

**Comment by Klap-in** [comment]
Please check the logs of your webserver. If you see where/which part prevent the webserver building your page, you know where to look. A lot of plugin made changes, but also a lot not yet. So it could still be a plugin that has issues. Looking these logs shows often what happens, check if a plugin is involved. You could check with this info at their wiki page or issue tracker if the issue is reported. If not, please file an issue at their issue tracker.

**Comment by phy25** [comment]
See https://www.dokuwiki.org/faq:blankpage for how to troubleshoot a blank page.
