### ISSUE TITLE
PHP insertion of a new group

### ISSUE THREAD

**Issue by Rainbow-Spike** [splitbrain/dokuwiki#3245]
Hello all. We use a group "user18" for protection of NSFW materials through ACL. Adult people can pass a mathematical captcha through a stand-alone PHP script for getting this group. It fopen/explode/fputs "user18" directly in string array from conf/users.auth.php. I try to insert it by a simple PHP way, so I set global $USERINFO, but $USERINFO [ 'grps' ] [ ] = 'user18' works only for online, this can't affect to account file. I tried to search in Usermanager plugin but can't fastly understand this black magic. Help me, please ._.

**Comment by phy25** [comment]
This is a more appropriate question for https://forum.dokuwiki.org/ as this is just a extension development question.

If you want to proceed with modifying `users.auth.php` then you need to parse the whole file rather than modifying only the array. Or, you should be able to call the respective auth API (`triggerUserMod`). A good starting point [could be here](https://github.com/phy25/dokuwiki-plugin-forceuserchange/blob/bbb2397ddb4dc098abcd84b6adf64812ccc4fab1/action.php#L117).

**Comment by Rainbow-Spike** [comment]
Thank you!

> you need to parse the whole file rather than modifying only the array
already done so:
`$file_array = file ( $userauth ); // acc file as string array
$fp = fopen ( $userauth, "w" ); // make empty and rewrite the acc file
for ( $i = 0; $i < count ( $file_array ); $i++ ) { // on each string
	$mas = explode ( ":", $file_array [ $i ] ); // ":" splitting
	if ( count ( $mas ) != 5 || $mas [ 0 ] != $user ) { // if not 5 parts = normal strings or all other users
		fputs ( $fp, $file_array [ $i ] ); // add as is
		continue;
	};
	if ( $mas [ 0 ] == $user ) { // if the string's first part matches the user
		fputs ( $fp, substr ( $file_array [ $i ], 0, -1 ) . ",user18\n" ); // add as is - '\n' + ",user18\n" in groups
	};
};
fclose ( $fp );`
it seems to me that this mechanism takes longer than just adding a group in a regular way
