### ISSUE TITLE
Make function tpl_pageinfo more configurable

### ISSUE THREAD

**Issue by obw** [splitbrain/dokuwiki#3305]
I'm preparing a page, which should use DokuWiki.

In this case the function tpl_pageinfo gives too much informations, I'm only allowed to show the date of change/create Date nothing more.

It was easy to comment out the not allowed Information in this function, but after the next update, I must do this again:(.

I think also this is something which should be handled in the templates!

I think it would be better to deprecate this function, in a first step. Also make the use of it configurable in the admin-module.

After this, the default Template should show how implement the output this Data.

And with the next or the major release after this, the function can be removed, without big issues of the Users, who use DokoWiki for years!

**Comment by phy25** [comment]
> I'm only allowed to show the date of change/create Date nothing more

This is what is currently being shown:

- file path - you can infer that by the browser path, so hiding it doesn't help
- date - also shown on revision page by default
- editor - also shown on revision page by default
- whom the file is locked by - also shown on edit page

DokuWiki could disable revision actions globally or limit page edit by ACL, but the single page level control is interesting.

> I think also this is something which should be handled in the templates!

You are free to modify the template not to use it and implement your own.

**Comment by obw** [comment]
> > I'm only allowed to show the date of change/create Date nothing more
> 
> This is what is currently being shown:
> 
>     * file path - you can infer that by the browser path, so hiding it doesn't help
>     * date - also shown on revision page by default
>     * editor - also shown on revision page by default
>     * whom the file is locked by - also shown on edit page
> 
> 
> DokuWiki could disable revision actions globally or limit page edit by ACL, but the single page level control is interesting.
> 
> > I think also this is something which should be handled in the templates!
> 
> You are free to modify the template not to use it and implement your own.
Which I have done, but this Information is not manipulatable in the templates by now! So I'm forced to manipulate the function and everytime I'm install a new Update, I must du it again!

**Comment by Klap-in** [comment]
> In this case the function tpl_pageinfo gives too much informations, I'm only allowed to show the date of change/create Date nothing more.

"too much"  "only allowed". 
With what kind of standard or requirements you are judging this? I try to understand your situation. Please note that a part of the info is quite trivial, it can be derived easy in another manner. 

Further it is a wiki, so how is this wiki working for you in practice, if you like to hide every meta info of a wiki page?

That suggestion of 'modifying' a template works as following:
- please be aware that the 'dokuwiki' template is the builtin template, which is maintained by the project. Which means also you will get updates. Updates means potentially replacing all original files of the template.
- you can make a clone of this template. This clone will not be overwritten on update.
- It is **important** to configure some basic info in your cloned template to prevent unexpected behaviour:
  - `template.info.txt` contains a line `base dokuwiki`, you have to **rename** it in your clone to `base mytemplate`. Where `mytemplate` is the foldername of your new template.
- Next you make your changes.
- If DokuWiki is upgraded, your cloned template is not changed. Of course, (maybe) some pieces don't work longer anymore. So you need to copy all code of the upgraded 'dokuwiki' template to your cloned template manually, during this copying you can keep care of all your own changes.

There are a lot of opinions and preferences for a template. Because it is difficult for us as developers to implement every option of that, you have the option to build your own template. Hopefully creating your template is easy enough.
