### ISSUE TITLE
Two dashes in a code block get combined into a single dash

### ISSUE THREAD

**Issue by doubledgedboard** [splitbrain/dokuwiki#3333]
If I have a code block such as

''Foo -- Bar''

then the displayed text ends up being

`Foo - Bar`

rather than

`Foo -- Bar`

Please understand how incredibly significant this problem is when you're trying to paste code/unformatted text.

**Comment by phy25** [comment]
I can't reproduce this:

https://www.dokuwiki.org/playground:codeblock

Could you provide more information such as what exact syntax you use, what version you are on, what plugin you have?

**Comment by doubledgedboard** [comment]
Version:
Release 2020-07-29 "Hogfather"

Plugins Enabled:
ACL Manager
Plain Auth Plugin
Configuration Manager
Extension Manager
Info Plugin
Note Plugin
oauth plugin
Popularity Feedback Plugin
Revert Manager
safefnrecode plugin
styling plugin
User Manager
usermanagerextended plugin
Wrap Plugin

Syntax Example:
```
==== Divine Light ====

''/say DL -- %t''
```

Rendered Example:
![image](https://user-images.githubusercontent.com/5682150/98745383-15483200-2379-11eb-9108-35f22f0bd220.png)

**Comment by phy25** [comment]
Now I can reprocude this: https://www.dokuwiki.org/playground:codeblock

**Comment by Klap-in** [comment]
Hi, please note that the monospaced text is actually no (in-line) code block

    ''Monospaced text, no code block''

There is a plugin that can improve this. I think a lot of people expect it is kind of inline code block. But for historical reasons it is not. Changing will effect existing current syntax, which needs %%  .. %% around e.g. `—`

**Comment by doubledgedboard** [comment]
So to confirm there is no officially supported "code block / unformatted text" feature? Thanks

**Comment by Klap-in** [comment]
You have to combine syntaxes, see changed post above.

**Comment by Klap-in** [comment]
If you would like to change default behavior of DokuWiki, you could use this plugin: https://www.dokuwiki.org/plugin:unformattedcode

**Comment by doubledgedboard** [comment]
`<code>` block works perfectly, thanks for explaining

**Comment by Klap-in** [comment]
I think all questions are addressed, so the issue could be closed?

**Comment by doubledgedboard** [comment]
So the double dashes getting converted to an emphatic dash is intentional?

**Comment by Klap-in** [comment]
Yes, indeed. I'm sorry that I did not explain that.

`''text''` is the syntax for only applying a monospaced textstyle.

The wiki has the feature to convert some shortcuts to nice html characters: https://www.dokuwiki.org/entities
One of these entities is double dash into a long dash. This replacement is just done, because `''...text..''` is just a layout style.

This interpretation of entities, and all other other interpretation of syntax, can be prevented in DokuWiki, by putting that piece of text in `%%` like: `%% ..text -- text **bold**%%`.
So together you can use this to have a kind of 'inline code snippets' in monospace formatting: `''%% your text -- %%''`.

If you do not like this default behaviour of DokuWiki you could install the unformattedcode plugin: https://www.dokuwiki.org/plugin:unformattedcode

(Alternative is that you just disable the `--` entity, but maybe you will find later another character that surprises you.
You can disable by adding `--`, with no text behind it, to your personal `conf/entities.local.conf`-file. )

Does this help?
