### ISSUE TITLE
WYSIWYG editor markdown

### ISSUE THREAD

**Issue by ccomin** [splitbrain/dokuwiki#3388]
Hello,

First, dokuwiki is a very good wiki system.

But I'd like to understand, why and especially in 2021, that the editing system doesn't fully take the official syntax of the Markdown language (simpler and faster)

While leaving the system already active, today I have to take all my notes again since dokuwiki doesn't support 100% Markdown, with the modules, it's even worse, because we have incomprehensible files in our files.

It's a bit of a pity, by the way, it's also a pity that the notes are only on ".txt" files, why doesn't dokuwiki support ".md".

Good continuation, hopefully there will be some progress on this little wiki system.

**Comment by Klap-in** [comment]
Hi! this sounds a bit as a lot of assumptions...
Because we had a history before 2021, and just changing is not cheap. Or do you have some free hours? ;-)

The current DokuWiki syntax is considered as more readable syntax if compared to other syntax's in use today. Of course, Markdown is now well known, but for some context: both are invented in ~2004. Some people have developed plugins for DokuWiki, which add with different manners support for Markdown. 
https://www.dokuwiki.org/plugin:markdowku
https://www.dokuwiki.org/plugins?plugintag=markdown#extension__table
Might be that some of these even support .md, but I cannot see which that was.

Some note from the past: https://github.com/splitbrain/dokuwiki/issues/1091

Other WYSIWYG editors: 
CKGEdit Plugin https://www.dokuwiki.org/plugin:ckgedit
An effort by Splitbrain, the main developer of DokuWiki:
WYSIWYG editor, still experimental, but translates directly from DokuWiki-syntax forward-backward. https://www.dokuwiki.org/plugin:prosemirror Needs some additional effort probably for daily use.

My guess is that your biggest challenge at the moment is to get your current .md-files in to your DokuWiki?

**Comment by Michaelsy** [comment]
> But I'd like to understand, why and especially in 2021, ...

The reason why many still miss so many features on DokuWiki is because there are many more people who want something than those who actively contribute here.

\- Michael Sy.
