### ISSUE TITLE
opensearch suggestions should lead directly to page

### ISSUE THREAD

**Issue by tommy-mor** [splitbrain/dokuwiki#3405]
I love that you added OpenSearch to dokuwiki that suggests page names directly from browsers.
When you select one of the given suggestions, it searches the wiki in the top search bar. That makes sense for normal searches, where you aren't going directly to the page name, as you intend to search the body of each page. 

When you select a suggestion, the suggestions it gives are page names. It leads you to the search results page, where you then have to click the page name again that you already intend to go to. 

Is there a setting for this that I'm missing? Would it be possible to add this as a feature? Is there a workaround?

Thank you for making/maintaining dokuwiki, I love it very much.

**Comment by splitbrain** [comment]
I don't think this is possible, because we can only return suggestions but those are then submitted via the search URL by the browser. The only solution I could think of is returning the suggestions with some special marker and then parse that marker in handling the search to directly redirect to the appropriate page...

**Comment by tommy-mor** [comment]
That's what I was thinking too. Do you think it would be too gross? TBH i'm not a huge fan of it... I could probably add that feature.
