### ISSUE TITLE
Adding Reverse DNS entry to revisions page

### ISSUE THREAD

**Issue by JM-Lemmi** [splitbrain/dokuwiki#3487]
It would be nice if in addition to the IP-address of the editing user, dokuwiki would look up the PTR record associated with the IP and save that too.

**Comment by splitbrain** [comment]
@mprins DokuWiki already does reverse lookups (unless disabled) when sending notifications and I don't think the GDPR has anything to say here, since we already save the IP address...

That being said, I don't see much value in logging this additional info, since it can easily be retrieved when needed. It would probably even be possible to write a plugin that adds this info to the recent changes view on the fly. The big disadvantage would be that we would have to extend the changelog format, possibly breaking any implementations on top of it. So I will close this as won't implement.
