### ISSUE TITLE
critical bug with unknown plugin: 1050 Table 'wikipage_has_files' already exists

### ISSUE THREAD

**Issue by zpartakov** [splitbrain/dokuwiki#3537]
Hi

I have a lot of errors on my webserver:
`stderr: PHP message: [critical] Wiki: Unable to migrate schema for the plugin: Wiki => SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'wikipage_has_files' already exists `

I've been grepping for 'wikipage_has_files' in whole dw (not only lib/plugins but really from dw basedir) without finding anything. Nevertheless, the wiki seems to work perfectly

It may be not dw itseIf but a plugin, as I have many:

`acl | authpdo | authplain | blog | bureaucracy | config | creole | csv | custombuttons | data | datasearchform | datatables | dw2pdf | extension | feed | gallery | git | goto | html5video | iframe | include | info | matomo | meta | move | news | note | nspages | odt | orphanswanted | pagelist | pagenav | popularity | revealjs | revert | rss | s5 | safefnrecode | shortcutkey | sqlite | styling | syntax.php | tag | todo | upgrade | usermanager | vshare`

I'm using
```
PHP 7.4.3
Debian GNU/Linux 8.11
```

Any idea or clue would be welcome, thanks

**Comment by phy25** [comment]
This is not DokuWiki error message. Do you have something other than DokuWiki installed?

Looking at https://github.com/search?q=%22Unable+to+migrate+schema+for+the+plugin%22&type=code it has something to do with phinx. It will be worth checking to see if you have sqlite or mysql database and trace there.

Since this is a bug tracker rather than help forum I'd invite you to ask for help somewhere else. forum.dokuwiki.org might be a good place to start even though I suspect if this is from DokuWiki at all.

**Comment by phy25** [comment]
btw phinx is part of cakephp. I would be shocked if a public DokuWiki plugin uses this framework.

**Comment by zpartakov** [comment]
Thanks so much and sorry for the disturbance!
