### ISSUE TITLE
Got Issues while make non numeric Lists

### ISSUE THREAD

**Issue by cxbignekoc** [splitbrain/dokuwiki#3682]
I copy a Text from Website into the Editor, the Original is a List as well.
I use normal List Edit by use the [*]. But at some Point its breaks and writes into a box.
I dont know why this happens after i save the Edits.

https://www.screencast.com/t/A8v8EvL7b

- **It disappears** when i manually hit Enter to jump to new Line and set manually the next Listpoint [*]

The Code looks like this, pretty normal for me. After List Point "Ixx" the issue happens:

```
**All Sample FX:**
These commands only **apply to samples and will have no effect on the Plugin or MIDI components** of an Instrument. When used in the **Master track**, the effect will be applied to all tracks.

	* -Axy - Set arpeggio, x/y = first/second note offset in semitones. Using 0 for x or y will use the original note.
	* -Uxx - Slide pitch up by xx 1/16ths of a semitone (01 is 1/16th of a semitone, 08 is half a semitone, 10 is a whole semitone).
	* -Dxx - Slide pitch down by xx 1/16ths of a semitone (01 is 1/16th of a semitone, 08 is half a semitone, 10 is a whole semitone).
	* -Gxx - Glide towards given note by xx 1/16ths of a semitone (01 is 1/16th, 08 is half, 10 is a whole,
	* -Vxy - Set vibrato (regular pitch variation), x = speed, y = depth.
	* -Ixx - Fade volume (-I01 0 to full volume, -I7F will do the same much faster).
   	* -Oxx - Fade volume out by xx volume units.
    	* -Txy - Set tremolo (regular volume variation), x = speed, y = depth.
    	* -Cxy - Cut volume to x after y ticks (x = volume factor: 0=0%, F=100%). Does not stop playback.
    	* -Sxx - Trigger sample slice number xx or offset xx.
    	* -Bxx - Play sample backwards (xx = 00) or forwards (xx = 01).
    	* -Exx - Set the position of all active Envelope, AHDSR, Fader and Stepper Modulation devices to offset xx.
    	* -Nxy - Set auto pan (regular pan variation), x = speed, y = depth.
```

**Comment by Michaelsy** [comment]
> But at some Point its breaks and writes into a box.
> After List Point "Ixx" the issue happens

See the different whitespaces at the beginning of the lines.

\- Michael Sy.

**Comment by Michaelsy** [comment]
It's surprising that you achieved any list formatting at all. Because you do not keep the [intended formatting](https://www.dokuwiki.org/wiki:syntax#lists) in any line.

\- Michael Sy.

**Comment by Klap-in** [comment]
The number of whitespace before * tells how many times that item of the list is indented.

Because indention is per two spaces, in the editor some help provided by trying to indent a line correctly. But this 'automatic' logic rather simple.

Copying from an external editor is a challenging case to cover. So here the user has to check the number of whitespace themself, and combining with typed items, I see it is a bit confusing.

The last part becomes a codeblock because DokuWiki treats everything with two spaces in the front as code block, if the pattern was not recognized before as being part of another syntax.

Without complex processing of pasted text, we cannot improve much here? I'm right? So I propose closing.
