### ISSUE TITLE
No format validation in dformat

### ISSUE THREAD

**Issue by FloridSleeves** [splitbrain/dokuwiki#3685]
There is no validation in the display of date in admin Configuration Settings, which is not user friendly and may get wrong by admins:

![image](https://user-images.githubusercontent.com/23695653/171584833-9007aba4-307b-49d1-a392-f112ad6e2d8b.png)
![image](https://user-images.githubusercontent.com/23695653/171585146-34371ee2-241b-49f7-b853-ceb150af6c1d.png)

**Comment by Michaelsy** [comment]
A validation in the sense of "is valid" or "is not valid" can obviously not be realized with reasonable effort. On the one hand, this is because such a check would be quite complex and potentially quite error-prone. But even worse: the check would also have to be platform-dependent. (See https://www.php.net/manual/en/function.strftime.php)

What would probably be feasible would be a test output, which would then be generated by the respective platform itself.

(But I don't expect any programmer to take care of this problem in the foreseeable future).

\- Michael Sy.

**Comment by phy25** [comment]
Maybe adding a preview next to the config would help, but because config is set up in a very general way, I don't know if we want to add preview to that very specific config.

**Comment by Michaelsy** [comment]
**BTW:** Incidentally, one may wonder whether the date formatting "kjijoj" is actually invalid. Of course, it does not make sense. But not making sense is not the same as invalid. It's like with a programming language. If a program conforms to the syntax rules, that doesn't mean it performs a useful function, or even the intended function.

\. Michael Sy.

**Comment by Klap-in** [comment]
For me it is not worth the effort to add such a preview. However, if it is contributed it is fine to consider.
