### ISSUE TITLE
 Undefined array key 1 in inc/auth.php

### ISSUE THREAD

**Issue by anders-eriksson** [splitbrain/dokuwiki#3695]
I have downloaded the stable version 2020-07-29 "Hogfather" and run install.php
Accepted the default values, but added a admin user

Then Install seems to work!
But when I open index.php I get this
`Warning: Undefined array key 1 in /customers/d/4/6/andis59.se/httpd.www/dokuwiki/inc/auth.php on line 78 Warning: Cannot modify header information - headers already sent by (output started at /customers/d/4/6/andis59.se/httpd.www/dokuwiki/inc/auth.php:78) in /customers/d/4/6/andis59.se/httpd.www/dokuwiki/inc/auth.php on line 431 Warning: Cannot modify header information - headers already sent by (output started at /customers/d/4/6/andis59.se/httpd.www/dokuwiki/inc/auth.php:78) in /customers/d/4/6/andis59.se/httpd.www/dokuwiki/inc/common.php on line 1975 `

Why and how to fix it?
// Anders

**Comment by dregad** [comment]
This warning still exists on 2022-07-31a Igor, with PHP 8.0 and 8.1:

> Warning: Undefined array key 1 in .../web/wiki/inc/auth.php on line 82

It occurs when `$_SERVER['HTTP_AUTHORIZATION']` is blank, so explode results in an array with a single element. but list expects 2.

**Comment by dregad** [comment]
This is actually not reproducible on my local DEV box. 

After some further analysis, I believe this is because the hosting provider of the DW instance where the problem consistently occurs, is configured to use PHP FPM (FastCGI).

Extract from $_SERVER at the point where the warning is triggered:
```
["REDIRECT_HTTP_AUTHORIZATION"]=> string(0) ""
["HTTP_AUTHORIZATION"]=> string(0) ""
```

https://github.com/splitbrain/dokuwiki/blob/1e4e47625a7c46816aa6070feafa9e423046e6fc/inc/auth.php#L69-L79

So HTTP_AUTHORIZATION  is set from REDIRECT_HTTP_AUTHORIZATION, and the code should check that it is not empty, in addition to being set.

Moreover, to be safe the code should specifically check for _Basic_ auth scheme, instead of making the assumption that it is, and do a substr(xxx, 6) to retrieve  the base64 encoded user/password.

PR follows.

**Comment by dregad** [comment]
Actually I just tested against *master* and the *undefined array key* warning is no longer present there.

I'll still propose an enhancement to ensure proper check for Basic auth.
