### ISSUE TITLE
inc/jpegmeta.php Error: Call to undefined function xml_parser_create() 

### ISSUE THREAD

**Issue by ryannathans** [splitbrain/dokuwiki#3741]
when uploading certain images with metadata - eg this one
[priest_in_peril.zip](https://github.com/splitbrain/dokuwiki/files/9330617/priest_in_peril.zip)

viewing the image on the page or with the media manager shows this error 

![image](https://user-images.githubusercontent.com/1307375/184465158-83b49e49-dc45-4848-9690-09c4d0550aab.png)

sample log

```
2022-08-13 01:41:14Error: Call to undefined function xml_parser_create() /live/site/www/wiki/inc/JpegMeta.php(1559)
    #0 /live/site/www/wiki/inc/JpegMeta.php(1103): JpegMeta->_parseMarkerXmp()
    #1 /live/site/www/wiki/inc/JpegMeta.php(622): JpegMeta->_parseAll()
    #2 /live/site/www/wiki/inc/JpegMeta.php(230): JpegMeta->getDates()
    #3 /live/site/www/wiki/inc/JpegMeta.php(155): JpegMeta->getDateField()
    #4 /live/site/www/wiki/inc/media.php(1157): JpegMeta->getField()
    #5 /live/site/www/wiki/inc/media.php(1186): media_getTag()
    #6 /live/site/www/wiki/inc/media.php(1207): media_file_tags()
    #7 /live/site/www/wiki/inc/media.php(962): media_details()
    #8 /live/site/www/wiki/inc/template.php(1479): media_tab_view()
    #9 /live/site/www/wiki/inc/template.php(1782): tpl_mediaFileDetails()
    #10 /live/site/www/wiki/inc/Action/Media.php(21): tpl_media()
    #11 /live/site/www/wiki/inc/template.php(100): dokuwiki\Action\Media->tplContent()
    #12 [internal function]: tpl_content_core()
    #13 /live/site/www/wiki/inc/Extension/Event.php(133): call_user_func_array()
    #14 /live/site/www/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #15 /live/site/www/wiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #16 /live/site/www/wiki/lib/tpl/mindthedark/main.php(110): tpl_content()
    #17 /live/site/www/wiki/inc/actions.php(27): include('...')
    #18 /live/site/www/wiki/doku.php(126): act_dispatch()
    #19 {main} 
   ```

**Comment by Klap-in** [comment]
xml_parser_create() is a built in php function. Not one defined by DokuWiki.
I assume the xml extension is missing in your php installation

**Comment by ryannathans** [comment]
that'll do it... fixed by installing php8.1-xml package - maybe that should be listed in the requirements on the website?

**Comment by Klap-in** [comment]
If setting up a wiki, it is checked when running the install.php. Afterward we are not checking anymore. 

Because it is a list of functions we are checking for existence, I do not know which php extension they belong to… probably with some googling to do. Sometimes it not for missing extensions, but blocked functions by admins of some webhostings.

https://github.com/splitbrain/dokuwiki/blob/042e7b39d409be6bd806c761306930c0dd4f0a02/install.php#L571

I guess this vanishing of extensions happens during updates of php versions on the server. 
I think it not worth to check that normally. But maybe it is an reasonable option to do it as part of the admin screen?

**Comment by splitbrain** [comment]
> But maybe it is an reasonable option to do it as part of the admin screen?

Not a bad idea, but should be tracked in its own issue.
