### ISSUE TITLE
Create this page text is no longer a link

### ISSUE THREAD

**Issue by bamyasi** [splitbrain/dokuwiki#3749]
Not sure whether this is a bug or a new feature but when opening a non-existent page in default template there is a message text printed:

"This topic does not exist yet
You've followed a link to a topic that doesn't exist yet. If permissions allow, you may create it by clicking on Create this page."

"Create this page" part of this message used to be a link opening in the embedded page editor. Now it is plain text, printed in bold font.

Also, in the Extension Manager, "Configuration Manager" link is broken in the following text message at the top of EM page:

"These are the templates currently installed in your DokuWiki. You can select the template to be used in the [Configuration Manager](http://localhost/wiki/start?do=admin&page=config)."

**Comment by fiwswe** [comment]
### First issue
I have just checked on a Hogfather WIKI using the default DokuWiki template:
The relevant HTML code is:
```
<h1 class="sectionedit1" id="this_topic_does_not_exist_yet">This topic does not exist yet</h1>
<div class="level1">

<p>
You've followed a link to a topic that doesn't exist yet. If permissions allow, you may create it by clicking on <strong>Create this page</strong>.
</p>

</div>
```
There are no links there. Not sure what you think has changed in Igor?

You create the new page from the menu on the right.

On Igor the HTML looks pretty much the same:
```
<h1 class="sectionedit1" id="this_topic_does_not_exist_yet">This topic does not exist yet</h1>
<div class="level1">

<p>
You've followed a link to a topic that doesn't exist yet. If permissions allow, you may create it by clicking on <strong>Create this page</strong>.
</p>

</div>
```

So either your expectations are wrong or you are requesting a new feature? Maybe you are confusing DokuWiki with other WIKI software which might work differently?


### Second issue
Note: You should really write a separate GitHub issue because this seems to be completely unrelated to your first problem!

On my Hogfather Wiki the link is shown in red like a broken link but it works correctly. So it's a cosmetic problem only.
On Igor I see no problem at all.

Can you give more details on the version of DokuWiki you are using and other relevant data about your setup?


fiwswe

**Comment by splitbrain** [comment]
Like @fiwswe I connot reproduce these issues.
