### ISSUE TITLE
farmer plugin - name of the animal

### ISSUE THREAD

**Issue by farmascript** [splitbrain/dokuwiki#3769]
Name of the animal like 'whatevername' works ok.
Name of the animal like 'whateverName': the animal is created correctly, but the !bang url is not working.

There seems to be an issue when you choose a camelCase name.

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.
