### ISSUE TITLE
PHP error when showing page revisions

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3782]
Hi,

Showing revisions can lead to internal PHP error. I am unable to reproduce this.
It happens on dokuwiki.org.

```
Error: Call to a member function attr() on int
An unforeseen error has occured. This is most likely a bug somewhere.
More info has been written to the DokuWiki error log.
```

Experience the bug : https://www.dokuwiki.org/playground:hello?do=revisions

**Comment by splitbrain** [comment]
Hmm, the problem occurs here:

https://github.com/splitbrain/dokuwiki/blob/9f48b7048bfe54113e7d2ea528e226b1e3e2ab1d/inc/Ui/PageRevisions.php#L83

When the revision is `null` for some reason, the `val()` method returns the current value instead of setting a value and returning a Form\Element.

Here's the changelog for that page:

[hello.changes.txt](https://github.com/splitbrain/dokuwiki/files/9663810/hello.changes.txt)

It seems the very first change has a weird format, where there's the string `html` instead of a timestamp. Which causes $rev to be empty.

I removed the line and now the page loads as expected. The next timestamp is in 2006 so I assume this weird thing has been there for years and I don't know how it happened.

I'd like to see if the error occurs for other pages as well. If so it might be worth figuring out how the weirdness got there and if it's a long fixed issue or still happening. It might also be worth to skip lines with unreadable timestamps...

@Klap-in @ssahara might want to look at this too.

**Comment by schplurtz** [comment]
Oh, I understand why I was not able to reproduce this. I simply happened to recreate a page whose history was broken.

> I removed the line and now the page loads as expected. The next timestamp is in 2006 so I assume this weird thing has been there for years and I don't know how it happened.

Since 2006. No other occurrence of this error in more than 15 years. This is most probably some manual edit/command line/script at that time that produced this unexpected line. 

I just tested all my `.changes` files with this Q&D ruby code and It did not reveal any problem (oldest page dates back to 2009 only). For me this issue is resolved and can be closed. I'll let you do it though in case you're willing to investigate. 

```ruby
#! /usr/bin/env ruby

require 'ipaddr'

class String
  def isIP?
    (self.match IPAddr::RE_IPV4ADDRLIKE) or
    (self.match IPAddr::RE_IPV6ADDRLIKE_COMPRESSED) or
    (self.match IPAddr::RE_IPV6ADDRLIKE_FULL)
  end
end

Dir["#{ARGV[0]}/**/*.changes"].each do |name|
  lineno=1
  File.readlines(name).each do |line|
    # "1519403648\t127.0.0.1\tE\tblocnote:un-truc\tztrulphcs\t[note en passant] \t\t41"
    ts, ip, op, id, user, sum, extra, sz = line.split( /\t/ )
    reasons=[]
    reasons << "not enough fields" if not extra
    reasons << "date" if ts !~ /^\d+/ or ts.to_i < 1072911600 #(1072911600 is jan 1 2004 0:0:0)
    reasons << "ip" if not ip.to_s.isIP?
    reasons << "type missing" if op.to_s == ''
    reasons << "ID missing" if id.to_s == ''
    reasons << "abnormal size" if sz and not sz.match /^[-+]?\d+/
    reasons << "user [#{user}]" if user and user.to_s != '' and not user.match /^[\w+][\w\d_.-]*$/
    #reasons << extra if extra # if what ???
    puts "#{ name }:#{ lineno } #{ reasons.join ', ' }" if not reasons.empty?
    lineno+=1
  end
end
```

**Comment by splitbrain** [comment]
Thanks for checking your install. I will close it for now.
