### ISSUE TITLE
feed.php: "TypeError: Cannot access offset of type string on string"

### ISSUE THREAD

**Issue by azett** [splitbrain/dokuwiki#3793]
Hi,

after upgrading to 2022-07-31a "Igor" (did that with the Upgrade Plugin) under PHP 8.0, the RSS feed is broken:
![grafik](https://user-images.githubusercontent.com/22837642/194776241-286cb851-1b29-458a-b0d2-15db376b356c.png)

Error log says:
> 2022-10-09 19:19:24	(...)/feed.php(428)	TypeError: Cannot access offset of type string on string
  #0 (...)/feed.php(96): rss_buildItems()
  #1 {main}

Did I do something wrong there?
Thx & all the best,
Arvid

**Comment by azett** [comment]
Errm...problem does not exist any more. Did not change anything to the DokuWiki installation, but the feed works properly again. Maybe some effect after the upgrade...?

Nevertheless, I'll close the issue since not reproducable.

**Comment by bttrx** [comment]
Hi Arvid! :-D
Same problem here.
I fixed it by downgrading PHP from 8.0.26 to 7.4.33 temporarily.
In the logs I find "PHP Warning: Illegal string offset 'abstract' in /var/www/vhosts/derdrittetag.de/int21h.rocks/www/feed.php on line 428".
This line reads `$content = $meta['description']['abstract'];"`.
Any idea?
Cheers,
Robert

**Comment by bttrx** [comment]
The only plugins I use so far are Move and Backlinks. Deactivation didn't make a difference.

**Comment by bttrx** [comment]
I traced the problem back by reducing the number of recent changes in the config.
So the problem seems to be caused by either the exclamation mark in the page's title or by the summary created by the Move plugin.
Looking further...
The line in the .changes file looks like this:
`1672317450	77.13.XXX.XXX	e	software:compushow_2000	bttr	↷ Links angepasst, weil Seiten im Wiki verschoben wurden		2`

**Comment by bttrx** [comment]
> Did not change anything to the DokuWiki installation

But you probably created new (recent) changes, which moved problematic changes out of RSS scope.
