### ISSUE TITLE
qsearch (pagename quicksearch) - bug when search word starts with lower case ü umlaut

### ISSUE THREAD

**Issue by Chris75forumname** [splitbrain/dokuwiki#3808]
I use Hogfather, Sprintdoc template, useheading: navigation.
I assume, qsearch is case-insensitive because that's how it works with ä, Ä, ö, Ö, Ü, but surprisingly NOT with ü as the first letter of the search word.
Example: If I search for "Übersicht" in pagenames (in my case: first heading in the page), I get the pages with "Übersicht" in the h1.
But, if I search for "übersicht", those are not found. However, equivalent search attempts do work with any other umlaut, except the lower case ü! So, I figure it to be a bug.
I tried to reproduce this bug on [demo.sprintdoc.de/](demo.sprintdoc.de/) but useheadings is configured differently, over there. Everything works fine in native pagenames. So, this bug seems to occur only when searching in h1 (with useheading on).

**Comment by Chris75forumname** [comment]
Thank you for testing this! If it was intentional, it would occur in the same way with all words, but it only happens to words which start with umlauts, which are random words in some languages.

**Comment by fiwswe** [comment]
You are right. Adding:
- `====== uebersicht G ======`
- `====== Uebersicht H ======`

yielded both as _Matching pagenames_ when searching for either `uebersicht` or `Uebersicht`. That is indeed inconsistent with the Umlauts.

No idea as to why this happens or how to fix it though. My guess: Whatever function determines the equality of different case letters (case-insensitive compare) does not correctly deal with non-ASCII characters. Maybe someone more familiar with the search code can chime in?

**Comment by splitbrain** [comment]
Does it happen with umlauts in the middle of the word, too? I'm a bit confused why it should only happen with words starting with an umlaut.

**Comment by Klap-in** [comment]
If searching ä, only äberhaupt and aäberhaupt are founded.
If searching ü, only überhaupt and aüberhaupt are founded.
If searching Ä, only Äberhaupt and aÄberhaupt are founded.
If searching Ü, only Überhaupt and aÜberhaupt are founded.

useheading:navigation.

The quicksearch does a call to ajax https://codesearch.dokuwiki.org/xref/dokuwiki/inc/Ajax.php?r=&mo=927&fi=41#41
which calls: https://codesearch.dokuwiki.org/xref/dokuwiki/inc/fulltext.php?fi=ft_pageLookup#ft_pageLookup

https://github.com/splitbrain/dokuwiki/blob/1287b4f5b9e6e23d2610137b3ce4fc420415ea70/inc/fulltext.php#L291-L296
https://github.com/splitbrain/dokuwiki/blob/1287b4f5b9e6e23d2610137b3ce4fc420415ea70/inc/fulltext.php#L358-L369

So `stripos()` does not case-insensitive matching of umlauts?

Should the use of collator improve this? First guess is that it should. This is available as easy functions since #3115.

**Comment by Chris75forumname** [comment]
Found the solution: just use `mb_stripos()` instead!

https://stackoverflow.com/questions/5487917/stripos-returns-false-when-special-characters-is-used

Now my search string "über" finds all pages named "Übersicht" in the qsearch. Easy fix!

**Comment by BorisRV** [comment]
I had a similar problem with Russian-language pages. Your decision helped.
https://forum.dokuwiki.org/d/20838-case-insensitive-quicksearch/5

**Comment by splitbrain** [comment]
@BorisRV @Chris75forumname @fiwswe  Could you guys please test if #3895 works for you?

**Comment by BorisRV** [comment]
Well... I'm new to github, I don't know if I did the right thing. Surely you can do it easier and there is a "download" button somewhere))))
Created a file __test/tests/inc/FulltextPageLookupTest.php_
and edited the original file _inc/fulltext.php_
And yes, it solves the problem.
