### ISSUE TITLE
CKGEdit Plugin - Code Blocks - space before >

### ISSUE THREAD

**Issue by michieltimmers** [splitbrain/dokuwiki#3839]
Hi,

I put the following line in Code Blocks

`if memory usage > 70% for 1 cycles then restart`

When I save this DW Editor all is fine. 

However when saved with the "CKG Editor" the space between "usage"  and ">" is removed and the line will be saved as"

`if memory usage> 70% for 1 cycles then restart`

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.
