### ISSUE TITLE
SearchIndex plugin does not work on Cloudron

### ISSUE THREAD

**Issue by philkunz** [splitbrain/dokuwiki#3870]
Hi,
the searchindex plugin does not work on Cloudron.
We migrated a huge wiki to Cloudron, but cannot update the search, since rebuilding the searchindex fails.
Another new dokuwiki install without cloudron just works in comparison.

**Comment by splitbrain** [comment]
Thank you for taking the time to create an issue. However, the problem you describe needs to be fixed in the extension's code and not in DokuWiki core. **Please open an issue at the extension's issue tracker**. You will find it linked from the appropriate extension page on dokuwiki.org.

Be sure to include as much info as necessary to help the extension author identify and fix the problem. See [How to report Bugs](https://www.dokuwiki.org/bugs) for more info on that.
