### ISSUE TITLE
Website certificate is out of date

### ISSUE THREAD

**Issue by MattTraina** [splitbrain/dokuwiki#3879]
I'm not sure if this should go here, so I apologize and can change it if need be. Figured I would start with a bug report and see where that gets me. 

As of today, and it's been a few days since I logged in, but I can no longer get to our docuwiki site. Our Fortinet is blocking it and thinking it is an illegal website. According to our IT who investigated it on the backend of our firewall, the certificate is now out of date from the hosting site. We would need to know what the SSL certificate is so we could manually get around it, or the best option is to have the certificate up to date. 

Thanks for reading!

![image](https://user-images.githubusercontent.com/56164635/216724966-92606352-24f1-47a1-a0aa-3d018401888b.png)

**Comment by splitbrain** [comment]
I have no idea what a Fortinet is or why your IT would send you here for a certificate problem with *your/their* hosting, but you're definitely wrong here. You should try talking to your IT again and not leave until they help you.

**Comment by Klap-in** [comment]
Which site do you mean? https://www.dokuwiki.org/dokuwiki?

![image](https://user-images.githubusercontent.com/183250/217080972-0e2df48c-8ad3-4f28-80de-205501104352.png)

So if you _really_ mean dokuwiki.org, then you have something in between you and dokuwiki.org that breaks it, because for others it works.
