### ISSUE TITLE
PHP 5.5 (Session is lost)

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#583]
just got this via email:

Recently switching our servers to PHP 5.5 we noticed that a login to the Dokuwiki instance does not work anymore, the session is lost after the redirect.

We debugged your the code and this is what needs to be changed to make Dokuwiki work on PHP 5.5:

When starting a session always check if the session is already active, otherwise PHP 5.5 will renew the session and that leads to loosing the previously opened session. That's why a login is lost:

Use this code to start a session:

```
            /*--PHP 5.5--*/
            if (version_compare(PHP_VERSION, '5.4.0') >= 0) {
                if (session_status()==PHP_SESSION_NONE) { session_start(); }
            } else {
                if(session_id()=='') { session_start(); }
            }
```

**Comment by multiscan** [comment]
I encountered a (probably unrelated) issue with the same effect: *login lost after redirect*.

In my case it was on a freshly installed dokuwiki, default template and no added plugins (something I have used in tens of cases before). 

Being a small wiki for internal use and only accessible from the local LAN, I did not bother setting up ssl/https on the web server. This turned out to be **the** problem. The session cookie was never sent back to the server because the `securecookie`  option is set to 1 by default.
 
Of course, had I checked the `dokuwiki.php` configuration file for defaults, I would have immediately figured out what was the problem but for some reason I was thinking that the problem was on my server's php-related configuration.

May it would be a good idea to explicitly set the option in the initial local.php configuration file or add an *https-enabled web server* among the [requirements](https://www.dokuwiki.org/requirements)

**Comment by splitbrain** [comment]
@multiscan as you say, your problem is unrelated. Also not true. The secure cookie option is only used when a site is served via SSL. DokuWiki runs fine on http with the option enabled. If you feel you encountered a bug please open a new ticket.

**Comment by phy25** [comment]
Closing since we no longer support PHP 5.5 and I don't see any newly posted issues about this.
