### ISSUE TITLE
PHP Warnings Crypt_Base.php on line 915

### ISSUE THREAD

**Issue by Django-BOfH** [splitbrain/dokuwiki#763]
I have a lot of error-messages like this one:

[Fri Jun 20 17:54:56 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 9
15
[Fri Jun 20 17:54:56 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 9
15
[Fri Jun 20 17:54:57 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:54:58 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:54:58 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:54:59 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:00 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:00 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:01 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:01 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:02 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915
[Fri Jun 20 17:55:02 2014] [error] [client aaa.bbb.ccc.ddd] PHP Warning:  mdecrypt_generic(): An empty string was passed in /var/www/dokuwiki/inc/phpseclib/Crypt_Base.php on line 915

I'm using Release 2014-05-05 "Ponder Stibbons". 

The IP adresses all foreign adresses, either there's a bug, a big fail in my settings, or someone is attacking my wiki. :/

**Comment by chang-zhao** [comment]
I'm trying to use Dual Login from JFusion integration with Joomla 3.
When I login in Joomla and go to DokuWiki page I get messages:

Warning: mdecrypt_generic(): An empty string was passed in C:\localhost\wiki\inc\phpseclib\Crypt_Base.php on line 915

Warning: Cannot modify header information - headers already sent by (output started at C:\localhost\wiki\inc\phpseclib\Crypt_Base.php:915) in C:\localhost\wiki\inc\auth.php on line 542

Warning: Cannot modify header information - headers already sent by (output started at C:\localhost\wiki\inc\phpseclib\Crypt_Base.php:915) in C:\localhost\wiki\inc\actions.php on line 217

Warning: Cannot modify header information - headers already sent by (output started at C:\localhost\wiki\inc\phpseclib\Crypt_Base.php:915) in C:\localhost\wiki\lib\tpl\dokuwiki\main.php on line 12


Actually JFusion seems to generate cookie "DW..." so I should login to DokuWiki, but it doesn't happen.
I set cookiedir to "/" (instead of "/wiki/"), so JFusion puts cookies ("/") where they should be read. I only wonder what's wrong.
Maybe some encoding method changed or some security measures meddled in?

**Comment by Klap-in** [comment]
It appears that there are certain set of users affected by this, but so far I could not find some shared pattern between them. Has someone suggestions?

**Comment by chang-zhao** [comment]
JFusion developer said: "Probably in a new DokuWiki release they changed authentication cookies again", so some discrepancy with a plugin appeared.

**Comment by casperklein** [comment]
For me, the problem went away. But I don't know exactly why. I guess the upgrade to the next release (I was on Ponder Stibbons when first posted here) or upgrading securelogin plugin fixed it for me.
Hope that helps a bit.

**Comment by Klap-in** [comment]
Do you have still PHP Warnings appearing from Crypt_Base.php in your DokuWiki?
