### ISSUE TITLE
Incorrect syntax highlighting for "diff"

### ISSUE THREAD

**Issue by schroedter** [splitbrain/dokuwiki#900]
DokuWiki has a bad syntax highlighting for "diff", because of missing css-styles for ".code .re7" and ".code .re8". Lines starting with "+" or "-" should be emphasize with colors green and red.

My suggestion for /lib/geshi.less:

```
.code {
    .re7 {
        background-color: #fbdcdb;
        color: #ff0000;
    }

    .re8 {
        background-color: #dcfbdb;
        color: #00b200;
    }
}
```

**Comment by Klap-in** [comment]
An example:
https://www.dokuwiki.org/plugin:deflist?s[]=code&s[]=diff#styles_conflicts_with_media_manager

Are these classes missing due to the reduction of the css for highlighting? Or should these styles be included?
(See also https://www.dokuwiki.org/tips:code_css)

**Comment by LarsGit223** [comment]
I added a pull-request to add the missing styles. I created the values from within dokuwiki so the styles are created from the Geshi version that dokuwiki is running:
- the text color is different from the suggestion above (but still green and red)
- no background color (my Geshi did not output a background color for classes re7 and re8)

> Are these classes missing due to the reduction of the css for highlighting?

Yes.

> Or should these styles be included?

I suggest to merge my PR for the following reasons:
- the current diff style is missing the red and green colors which is the most important part of highlighting diff code
- actually diff code is hard to read because the colors are missing. Especially if the code is indented several levels (as the example referenced by @Klap-in shows).
- dokuwiki.org would benefit from it as it also includes some highlighted diff code e.g. on the plugin pages
