### ISSUE TITLE
Inlinecode with double singel quotation marks breaks if it contains double slashes.

### ISSUE THREAD

**Issue by mogoh** [splitbrain/dokuwiki#941]
Like this: ''//''

**Comment by selfthinker** [comment]
I have an old wiki somewhere (not updated since 2014) and noticed today that `''//''` was working fine back then. It was rendered into as `<code>//</code>`. I guess something happened in 2014 that changed this.

While testing this now on an up-to-date version, I also noticed that the same is not happening with other formatting. For example `''**''` does not make everything bold after it. Or `''##''` doesn't start a heading.
That is at least inconsistent. I'm not sure if this inconsistency is enough to reopen the issue?

(And annoyingly, my [UnformattedCode plugin](https://www.dokuwiki.org/plugin:unformattedcode) doesn't fix it either. I'm pretty sure it used to do that.)

I suspect the reason why italic is treated differently than any other formatting is to do with link parsing?

**Comment by phy25** [comment]
@selfthinker I have done a quick test on `tags/release_stable_2012-01-25` (I also tried a version in 2014) and `master`, rendering the following wikitext:

```
000

''//'' 123

456

''**'' 123

~~NOCACHE~~
```

They render the same thing:

```html
<p>
000
</p>

<p>
<code><em><code> 123

456

</code>**&#039;&#039; 123


</p>
```

So I believe the behavior hasn't been changed recently at all.
